### ISSUE TITLE
installed firebase 

### ISSUE THREAD

**Issue by TrackYourExpense668** [angular/angularfire2#1135] opened 2017-09-01 08:02 UTC
getting error when  in ionic project during build process
---------------------------------------------------------------------------

1. i created a demo ionic project
2. installed the firebase and angularfire2 
3. imported 

 AngularFireModule.initializeApp(firebaseConfig),
 AngularFireDatabaseModule,

then build using command 
**ionic cordova build android --prod**

  bellow error showing .... 

**Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/database' in '/Users/abinash/Desktop/Demo/src/app'
resolve '../../angularfire2/database' in '/Users/abinash/Desktop/Demo/src/app'
  using description file: /Users/abinash/Desktop/Demo/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/abinash/Desktop/Demo/package.json (relative path: ./src/app)
    using description file: /Users/abinash/Desktop/Demo/package.json (relative path: ./angularfire2/database)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/abinash/Desktop/Demo/angularfire2/database doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/abinash/Desktop/Demo/angularfire2/database.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/abinash/Desktop/Demo/angularfire2/database.ts doesn't exist
      as directory
        /Users/abinash/Desktop/Demo/angularfire2/database doesn't exist
[/Users/abinash/Desktop/v/Demo/database]
[/Users/abinash/Desktop/Demo/angularfire2/database.js]
[/Users/abinash/Desktop/Demo/angularfire2/database.ts]
[/Users/abinash/Desktop/Demo/angularfire2/database]
 @ ./src/app/app.module.ngfactory.js 30:0-56
 @ ./src/app/main.ts**

if iam using the command **ionic cordova build**  then perfectly working

**Comment by littlemercury** [comment] 2017-09-01 08:49
This is an issue with rc2. Reverting to rc1 will fix this. 
Delete your node_modules directory, revert to rc1 and run npm install.

**Comment by littlemercury** [comment] 2017-09-01 08:50
This is a duplicate of this issue - https://github.com/angular/angularfire2/issues/1124

**Comment by davideast** [comment] 2017-09-01 15:12
Closing in favor of original.

**Closed by davideast** 2017-09-01 15:12 UTC
