### ISSUE TITLE
Cannot find module '@firebase/app-types/private'.

### ISSUE THREAD

**Issue by manojkumarbehera** [angular/angularfire2#1419] opened 2018-01-11 16:48 UTC
node_modules/@firebase/database/dist/esm/src/api/Database.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types/private'.
node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts(17,39): error TS2307: Cannot find module '@firebase/app-types/private'.
node_modules/angularfire2/auth/auth.d.ts(10,20): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/auth/auth.d.ts(11,36): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/database/database.d.ts(7,15): error TS2503: Cannot find namespace 'database'.
node_modules/angularfire2/database/interfaces.d.ts(3,50): error TS2503: Cannot find namespace 'firebase'.

**Comment by davideast** [comment] 2018-01-11 16:51
Duplicate of #1387. Waiting until the next firebase release and we'll have it fixed hopefully today or tomorrow.

**Closed by davideast** 2018-01-11 16:51 UTC

**Comment by abubakarmuneer** [comment] 2019-02-03 17:40
Failed to compile.

node_modules/angularfire2/angularfire2.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types'.
node_modules/angularfire2/auth/auth.d.ts(1,36): error TS2307: Cannot find module '@firebase/auth-types'.
node_modules/angularfire2/auth/auth.d.ts(2,33): error TS2307: Cannot find module '@firebase/app-types'.
node_modules/angularfire2/database/database.d.ts(2,34): error TS2307: Cannot find module '@firebase/database-types'.
node_modules/angularfire2/database/database.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types'.
node_modules/angularfire2/database/interfaces.d.ts(1,67): error TS2307: Cannot find module '@firebase/database-types'.
node_modules/angularfire2/database/list/audit-trail.d.ts(3,30): error TS2307: Cannot find module '@firebase/database-types'.
node_modules/angularfire2/database/list/state-changes.d.ts(5,30): error TS2307: Cannot find module '@firebase/database-types'.
node_modules/angularfire2/firebase.app.module.d.ts(2,62): error TS2307: Cannot find module '@firebase/app-types'.
node_modules/angularfire2/firebase.app.module.d.ts(3,30): error TS2307: Cannot find module '@firebase/auth-types'.
node_modules/angularfire2/firebase.app.module.d.ts(4,34): error TS2307: Cannot find module '@firebase/database-types'.
node_modules/angularfire2/firebase.app.module.d.ts(5,35): error TS2307: Cannot find module '@firebase/messaging-types'.
node_modules/angularfire2/firebase.app.module.d.ts(6,33): error TS2307: Cannot find module '@firebase/storage-types'.
node_modules/angularfire2/firebase.app.module.d.ts(7,35): error TS2307: Cannot find module '@firebase/firestore-types'.

**Comment by abubakarmuneer** [comment] 2019-02-03 17:43
can anyone help me to resolve this issue firebase package is not found in node modules  ....I also  type this command  npm i --save firbase@4.10.0 angularfire2@4.0.0-rc.1
