### ISSUE TITLE
 Error: Can't resolve all parameters for AngularFirestore: ([object Object], ?).

### ISSUE THREAD

**Issue by KSingh1980** [angular/angularfire2#1435] opened 2018-01-23 18:55 UTC
Test Case is failing==> **Error: Can't resolve all parameters for AngularFirestore: ([object Object], ?).**

Code gets compiled and everything but test is failing.

fdescribe('FirestormService', () => {
 

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [FirestoreService,AngularFirestore,AngularFireModule,AngularFirestoreModule],
      imports: [
     
        AngularFireModule.initializeApp(environment.firebase)
      
      ],
    });
  });
  
  it('should be created', inject([FirestoreService], (service: FirestoreService) => {
    expect(service).toBeTruthy();
    console.log('FirestoreService created==>True');
  }));

package json

 "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/speakeasy": "^2.0.1",
    "angularfire2": "5.0.0-rc.3",
    "core-js": "^2.4.1",
    "firebase": "4.8.0",
    "qrcode": "^1.0.0",
    "rxjs": "^5.5.5",
    "speakeasy": "^2.0.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.3",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by davideast** [comment] 2018-01-23 18:57
Duplicate of #1206.

The `next` release should fix this. Try installing `npm i angularfire2@next`.

**Closed by davideast** 2018-01-23 18:57 UTC
