### ISSUE TITLE
Error while building "Cannot find namespace 'firebase'"

### ISSUE THREAD

**Issue by kanishkatn** [angular/angularfire2#541] opened 2016-09-21 10:30 UTC
Hi,

I am getting the following error while building the project. Please help 

> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/database/database.d.ts:9:28 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/database/database.d.ts:10:30 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:15:39 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:16:51 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:16:91 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:17:50 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:17:118 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth.d.ts:20:55 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth_backend.d.ts:6:81 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth_backend.d.ts:8:48 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth_backend.d.ts:13:45 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth_backend.d.ts:41:10 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/providers/auth_backend.d.ts:61:54 
> Cannot find namespace 'firebase'.
> 
> ERROR in [default] /Users/kanishkanagaraj/JeetLab/BetMe/web/node_modules/angularfire2/utils/firebase_list_factory.d.ts:5:73 
> Cannot find namespace 'firebase'.

I am using the following
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64
npm: 3.10.7

**Comment by Znow** [comment] 2016-09-21 10:52
+1

**Comment by davideast** [comment] 2016-09-21 11:07
Duplicate of #529. See the work around in the thread. We're working on a real solution.

**Closed by davideast** 2016-09-21 11:07 UTC

**Comment by hiepxanh** [comment] 2016-09-29 02:07
import * as firebase from 'firebase';
on top of node_modules\angularfire2\angularfire2.d.ts
worked!

**Comment by mpeguero** [comment] 2016-10-31 18:23
import * as firebase from 'firebase';
on top of node_modules\angularfire2\angularfire2.d.ts

This does not work.. same error

**Comment by reevr** [comment] 2018-01-09 07:52
I too had this problem and I tried adding " import * as firebase from 'firebase' " . This helped me to get the app compiled, but was throwing error while geting data from firebase.So removed that again.
And I just changed one line in app.module.ts as follows:
to import AngularFireDatabase I used " import { AngularFireDatabase } from 'angularfire2/database-deprecated'; " instead of " import { AngularFireDatabase } from 'angularfire2/database'; "

This works fine and doesn't throw any error as of now.
