### ISSUE TITLE
angular/common@2.0.0-rc.3 incompatible

### ISSUE THREAD

**Issue by MrBokeh** [angular/angularfire2#371] opened 2016-07-20 02:08 UTC
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
npm ERR! peerinvalid Peer angularfire2@2.0.0-beta.2 wants @angular/common@2.0.0-rc.2
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.10 wants @angular/common@^2.0.0-rc.3

**Comment by openminder** [comment] 2016-07-21 06:04
I think this duplicates #325

**Comment by davideast** [comment] 2016-07-21 12:08
Duplicate of #325

**Closed by davideast** 2016-07-21 12:08 UTC
