### ISSUE TITLE
Transactions refresh listing in Safari/iOS

### ISSUE THREAD

**Issue by ix-xerri** [angular/angularfire2#844] opened 2017-02-27 18:49 UTC
### Version info

**Angular:**
2.3.1 (tried on 2.4.8)
**Firebase:**
3.3.0
**AngularFire:**
2.0.0-beta.8
**Other (e.g. Node, browser, operating system) (if applicable):**
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
### Test case

Whenever you try to implement a transaction the list gets refreshed inside Safari / iOS (in ionic 2 - tested on device). I notice it because part of my list is an image url. Anything that changes in the transaction, the image get reloaded.

This is the function that is called when you click a button. The action is for a simple like button. If you click the like button twice, it unlikes and image. Simple Instagram scenario here. Work normal in Chrome. Note that there are no transaction in Angularfire.

    this.workoutLikes =  this.af.database.object('/workouts/' + this.workout.$key + "/likes/" + email);

    // Called by a 'like' button
    toggleLike(){
        this.workoutLikes.$ref.transaction((likes) => {
          return likes ? likes + 1 : 1;
        });
    }`

Note that this does not happen when testing on Chrome. Also if I just return 'likes' the image won't get refreshed. So the image gets refreshed when the likes number change.

Anyone else facing a similar issue?

**Comment by davideast** [comment] 2017-03-16 11:28
Hey @ix-xerri! Can you create a plnkr showing the problem?

**Comment by ix-xerri** [comment] 2017-03-16 19:02
Sorry but its a bit difficult to recreated a working example.

`toggleLike(){
    this.workoutLikes.$ref.transaction((likes) => {
      return likes ? likes + 1 : 1;
    });
  }`

`<button ion-button icon-left clear small (click)="toggleLike()">
      <ion-icon name="thumbs-up" [color]="likeColor"></ion-icon>
      <div>{{ numLikes }} Likes</div>
    </button>`

With just the above code, the workout image get refreshed. In `toggleLike()` if I return `likes` and not add 1 to the value, the image does not get refreshed. Note that this does not happen on chrome.

**Comment by ix-xerri** [comment] 2017-03-18 21:29
I am reworking how it works. It seems that the data is reloaded when an update to the object occurs. The problem is that when that data is updated, in redownloads the image. 

This issue can be closed.

**Comment by Toxicable** [comment] 2017-03-23 03:44
@ix-xerri if the issue is resolved then you are able to close it yourself

**Comment by ix-xerri** [comment] 2017-03-23 03:49
I am currently looking at http://stackoverflow.com/questions/42178592/in-firebase-do-i-really-have-to-download-an-entire-node-in-order-store-somethin since a I want to stop a node being refreshed when an update happens but it is still happening so it is not solved.

**Comment by davideast** [comment] 2017-03-23 17:24
Your questions has been answered on SO. This is a Firebase SDK question not an AngularFire2 one.

**Closed by davideast** 2017-03-23 17:24 UTC

**Comment by ix-xerri** [comment] 2017-03-23 17:40
It because Firebase SDK question because of _"creating an AngularFire2 observable will download the items at that location"_. Do you know if there is a way around this and not download the entire node every time there is an update on 1 variable?

**Comment by osnircunha** [comment] 2017-08-11 02:21
I know it is old but just in case others come to here like me googling for a solution, I could solve this problem on Safari by adding $event to click method call and then event.stopPropagation() inside the  function.

**Comment by FiringBlanks** [comment] 2018-04-08 10:16
@ix-xerri  Did you figure this out? I'm using Angular 5 w/ AngularFire2 and every transaction seems to refresh the entire component which causes it to fetch data for a different tab (in the case of multiple tabs) and use those values for the refreshed tab when it comes back a second later. Dialogs (I'm using Material 2) triggering a transaction are also refreshed entirely, causing them to blink momentarily and resubscribe to my rxjs observables that are happening in ngOnInit(). This is horrible.

**Comment by ix-xerri** [comment] 2018-04-08 12:50
Currently not using transactions. Normal angularfire2 observables with an ionic refresher.
