### ISSUE TITLE
Connecting to two Firebase Apps

### ISSUE THREAD

**Issue by danielfliegauf** [angular/angularfire2#846] opened 2017-02-28 10:34 UTC
The Firebase Docs describe quite nicely how to connect to two different apps.

// Initialize the default app
firebase.initializeApp(defaultAppConfig);

// Initialize another app with a different config
var otherApp = firebase.initializeApp(otherAppConfig, "other");

console.log(firebase.app().name);  // "[DEFAULT]"
console.log(otherApp.name);        // "other"

// Use the shorthand notation to retrieve the default app's services
var defaultStorage = firebase.storage();
var defaultDatabase = firebase.database();

// Use the otherApp variable to retrieve the other app's services
var otherStorage = otherApp.storage();
var otherDatabase = otherApp.database();

I found on your GithubPages the following:
https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#custom-firebaseapp-names

But how do i get a reference within ng2 to this two firebase-apps? Could you maybe update your documentation? 

Thank you a lot and 👍 for all this awesome work!!
Daniel

**Comment by mukesh51** [comment] 2017-02-28 19:26
@danielfliegauf Not sure if I got your question, but are you asking how to connect to firebase from your angular2 App. Also, you're not following the issue template.

**Comment by danielfliegauf** [comment] 2017-03-02 11:13
Hi Mukesh,
thanks for the quick reply.
I am using angularFire2 version beta0.7.

**My Question is: 
"How can I connect in an Angualar2 app to two different Firebase Apps/RealTimeDatabases using angularFire2?"**


¯\_(ツ)_/¯---------------------------------------------------------

This is probably not right, is it?

@NgModule({
  imports: [
    BrowserModule,
    AngularFireModule.initializeApp(firebaseConfig, authConfig, 'my-app-name'),
    **_AngularFireModule.initializeApp(firebaseConfig2, authConfig2, 'my-app-name2')_**
  ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}

**Comment by projetpos** [comment] 2017-04-24 18:14
up,
plase help us

**Comment by jaimealsilva** [comment] 2017-07-19 16:09
Checkout https://github.com/angular/angularfire2/issues/761

**Comment by Toxicable** [comment] 2017-09-01 20:15
appears to be a duplicate of #761 

can be closed

**Comment by biowheel** [comment] 2017-09-29 15:22
@danielfliegauf . How did you solve the issue? While there have been many answers given, somehow I am not getting it. I was also wondering if we have to add the initialize method twice. How did you go about solving the issue? Thanks.

**Closed** 2017-10-02 18:33 UTC
