### ISSUE TITLE
Conflict with @angular BrowserAnimationsModule when routing after authentication

### ISSUE THREAD

**Issue by kelle62819** [angular/angularfire2#1054] opened 2017-07-03 15:11 UTC
### Version info
**Angular:** 
@angular/cli: "1.2.0"

**Firebase:** 
firebase": "4.1.3",

**AngularFire:**
 angularfire2: 4.0.0-rc0

### How to reproduce these conditions
**Steps to set up and reproduce**

**Add Angular animations and angularfire to angular-cli project:**
- `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`
**Navigate on Login**
-  Call router.navigate to change routes after logging in with AngularFireAuth 
`this.afAuth.auth.signInWithPopup(new firebase.auth.FacebookAuthProvider()).then((data) => {
   this.router.navigate(['/lobby']);
  });			
}`

### Expected behavior

After login/navigate show only component for new route

### Actual behavior

After login/navigate components for previous roure and new route are shown. After 10-25 seconds the previous route disappears. If you do multiple successive login/logouts that navigate between Home route and Lobby route the Home and Lobby components multiply
Before:
![before](https://user-images.githubusercontent.com/2489621/27798643-5502ac64-6012-11e7-86fb-e53162cda347.png)
After-Login:
![after-login](https://user-images.githubusercontent.com/2489621/27798645-553a82b0-6012-11e7-94fe-e468340af1cb.png)
20 Seconds after login:
![20-seconds-after-login](https://user-images.githubusercontent.com/2489621/27798647-55b58000-6012-11e7-8a6b-5678408ef178.png)
After multiple login/logouts
![after-multiple-login-logouts](https://user-images.githubusercontent.com/2489621/27798642-54ed27ea-6012-11e7-9c89-8978d860bb97.png)

**Comment by davideast** [comment] 2017-07-07 16:23
@kelle62819 Can you create an github repo that reproduces this? If so I'll be happy to take a look.

**Comment by kelle62819** [comment] 2017-07-07 18:35
Here you go: https://github.com/kelle62819/conflict
You should see the behavior described. When you take out the BrowserAnimationsModule everything works properly.

Thanks for looking at this.

**Comment by kelle62819** [comment] 2017-07-13 10:05
@davideast Were you able to reproduce this?

**Comment by karlvd** [comment] 2017-07-28 20:28
I experience the same issue, I use the BrowserAnimationsModule and experience ~20 delay when routing, I also notice that the delay occurs when changing things in the template with a variable.
For example;
`this.afAuth.auth.signInWithPopup(new firebase.auth.FacebookAuthProvider()).then((data) => { 
this.showThing = true;`

And in the template you have 
`<div * ngIf="showThing">show me</div>`

So for some reason is seems that change detection is not triggered for a while after the promise resolves.

It´s possible to workaround it by manually triggering change detection for dom manipulation
```
`import { ChangeDetectorRef } from '@angular/core';`

constructor(    
    private cd: ChangeDetectorRef
  ) 

this.afAuth.auth.signInWithPopup(new firebase.auth.FacebookAuthProvider()).then((data) => { 
this.showThing = true;
this.cd.detectChanges();
```
Unfortunately it doesn´t work while routing since you are leaving the view and no code after the routing statement will execute, and you can´t trigger change detection in the new view until it´s rendered.

No solution really but I thought it might help and may be easier to troubleshoot looking at change detection with a simple template manipulation than with routing.

**Comment by sudhan-impekable** [comment] 2017-08-09 15:00
+1

**Comment by sudhan-impekable** [comment] 2017-08-17 11:56
+1

**Comment by ChakrounAnas** [comment] 2017-09-25 14:02
I have exactly the same issue !

**Comment by davideast** [comment] 2017-10-02 18:19
@kelle62819 Can you try the latest version and see if this is still a problem?

`npm i angularfire2@next`

**Comment by kelle62819** [comment] 2017-10-04 07:53
I tried upgrading and am running into this error: (not my post, but I am getting the same error)
https://stackoverflow.com/questions/46557694/update-issues-in-angularfire-5-0

**Comment by davideast** [comment] 2017-10-17 19:08
@kelle62819 You need to also upgrade to Firebase `4.5.0`. Let me know if that works.

**Comment by davideast** [comment] 2017-10-18 16:05
Closing but feel free to open a new issue if the problem exists.

**Closed by davideast** 2017-10-18 16:05 UTC

**Comment by javier-lerones-gallego** [comment] 2017-11-07 19:25
I've been very frustrated about this issue. It was happening to me too even when I updated to Angular 5.0.0, AngularFire2 5.0.0-rc.3, and firebase 4.6.1; 

I have a login component that does a `this.router.navigate(['dashboard'])` on successful firebase google login, however both the sign in component and the dashboard components are rendered after the routing event triggers a few seconds after the popup closes. And it only happens when I add the `BrowserAnimationsModule` to the project. If I remove the module everything works fine.

I tried `setTimeout()` but it didn't help. I was ready to give up, either choosing to not use the animations module, or to replace the signin setup with a dropdown auth component on the navigation bar on my dashboard instead, however I was googling something else when I found NgZone and I managed to make my desired setup work fine by using `zone.run()` like:

```typescript
this.afAuth.auth.signInWithPopup(this.googleProvider)
      .then((result) => {
        // ...

        // Redirecting without this.zone.run() messes up routing, and change detection
        this.zone.run(() => {
          this.router.navigate(['/', 'app', 'dashboard']);
        });
      })
```

It works for me! no 20 second delay to route, no issues with the 'from' component being left in the DOM, and all my animations work fine!

I hope this helps
