### ISSUE TITLE
ERROR TypeError: Object(…) is not a function” using AngularFirestore and firebase

### ISSUE THREAD

**Issue by Zediz** [angular/angularfire2#1668] opened 2018-05-17 16:09 UTC
I want to use firebase and angularfire2 in my app, first of all, I installed them, and for the declarations:

in environment.ts

```
export const environment = {
    production: false,
    firebase: {
    apiKey: 'sfsdfdsff',
    authDomain: 'sfsdfdf',
    databaseURL: 'https://ng-sfsdfsf.firebaseio.com',
    projectId: 'ng-fitnesssfsdfdsf',
    storageBucket: 'ng-fsdfsdfsfdecff5.appspot.com',
   messagingSenderId: '21331323'
   }
  };
```
in app.module.ts, imports:

```
AngularFireModule.initializeApp(environment.firebase),
AngularFirestoreModule
```
in the component where want to get my data:

`import { AngularFirestore } from 'angularfire2/firestore';`

until this moment I have not an error, but when I want to declare my variable in the constructor to use it:

```
constructor(private trainingService: TrainingService, private 
db:AngularFirestore) { }
```
I have an error:

```
ERROR TypeError: Object(...) is not a function
at eval (firestore.js:28)
at ZoneDelegate.invoke (zone.js:388)
at Zone.run (zone.js:138)
In my package.json:

"angularfire2": "^5.0.0-rc.8.0",
"core-js": "^2.4.1",
"firebase": "^5.0.2",
```
and I don't know why?

thanks for your help

**Comment by jaufgang** [comment] 2018-05-17 16:43
Same here.  I am getting this error on a previously working project after upgrading angularfire2 from `rc.4` to `rc.9`

**Comment by rahulshrm2109** [comment] 2018-05-17 18:06
I'm also getting same after updating to rc.9 also.

**Comment by hgchrre** [comment] 2018-05-17 18:15
Same here after updating to rc.9
I also happen to use Ionic v3

**Comment by diego-lipinski-de-castro** [comment] 2018-05-17 22:16
Same here

**Comment by jaufgang** [comment] 2018-05-17 22:27
Help us @davideast,  you're our only hope!

**Comment by diego-lipinski-de-castro** [comment] 2018-05-17 22:32
rc8 is broke, r7 gives zone already loaded error, the only solution is go to rc4, because  zone already loaded error happens until de rc7

**Comment by jamesdaniels** [comment] 2018-05-17 22:32
It mentions `firestore.js:28` which is `of(false)`; of being imported from `rxjs/observables`. What version of RXJS are you using? RCs 8 & 9 are only compatible with RXJS 6.

**Comment by diego-lipinski-de-castro** [comment] 2018-05-17 22:34
reference https://github.com/angular/zone.js/issues/1081

**Comment by jamesdaniels** [comment] 2018-05-17 22:36
@diego-lipinski-de-castro let's please keep the conversation to the error at hand.

**Comment by jamesdaniels** [comment] 2018-05-17 23:06
Closing for now, since I'm 99% sure that's what the issue is.

**Closed by jamesdaniels** 2018-05-17 23:06 UTC

**Comment by diego-lipinski-de-castro** [comment] 2018-05-17 23:16
Yeah, solved this issue, the problem now is with rxjs =>  Cannot find module "rxjs-compat/Observable"

**Comment by jamesdaniels** [comment] 2018-05-17 23:49
@diego-lipinski-de-castro are you the one trying to import Observable or is it a lib? Observable can be imported from rxjs: `import { Observable } from 'rxjs'`, if it's not you including you'll want to hunt down the library having troubles and file bugs with them.

**Comment by jamesdaniels** [comment] 2018-05-17 23:52
For reference here's the [RXJS 5 => 6 migration guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md).

**Comment by diego-lipinski-de-castro** [comment] 2018-05-18 00:12
I needed to install rxjs-compat, after that I updated all packaged and it's working

**Comment by vandres** [comment] 2018-09-11 15:58
Will it be possible to use this library also without rxjs-compat?

**Comment by OliveIT** [comment] 2019-01-13 07:32
Thank you, Nox04.

**Comment by jhonnathanH** [comment] 2019-01-24 23:47
thx Nox04 u save me

**Comment by JoAlgorithm** [comment] 2019-06-25 19:31
@Nox04  am facing this issue after install rxjs, can u help me pls ???

 in ../../node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' e                                                                                                                xpected.
../../node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected

**Comment by Fjnova** [comment] 2019-09-18 11:47
with me, I can fix it by adding the bold line:

 imports: [
    CommonModule,
    SharedModule,
    AngularFireModule.initializeApp(environment.firebaseConfig),
    **AngularFireStorageModule**
  ],

**Comment by ValentinLeander** [comment] 2019-10-15 08:51
@Fjnova Thanks, had the same issue with production mode and that solved it!

**Comment by BadTasTe-** [comment] 2019-11-18 10:58
In my case the error was Object(...).auth is not a function, so adding the AngularFireAuthModule solved the issue and production build is now working, thank you to @Fjnova for the hint

**Comment by lucianobrunet** [comment] 2020-02-17 01:13
Thanks @Fjnova, I was crazy trying to find the solution to this problem, finally I was missing the importation of AngularFireAuthModule and AngularFirestoreModule
