### ISSUE TITLE
auth.login() Error "location.protocol" must be http or https

### ISSUE THREAD

**Issue by Chuckv01** [angular/angularfire2#279] opened 2016-06-23 22:11 UTC
`auth.login()` has an error when attempting to authenticate with Google or Facebook on an iOS or Android device using Cordova.

Here is a code sample:

```
this.af.auth.login({
  provider: AuthProviders.Google,
  method: AuthMethods.Popup
}).then((value) => {
  //success
}).catch((error) => {
  console.log(error);
});
```

Running version `2.0.0-beta.3-0930330` of angularfire2.

When run in a Cordova app the error callback will be called with this message:

![screenshot_2016-06-23-15-04-51](https://cloud.githubusercontent.com/assets/1181306/16321829/fad602f8-3953-11e6-99f4-0f648bc2f645.png)

**Comment by quentinchap** [comment] 2016-06-24 20:21
Same that #270

**Comment by jeffbcross** [comment] 2016-06-25 00:26
Yikes, seems like `signInWithPopup()` has the same protocol check as `getRedirectResult()`. https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithPopup

I'm a little out of my depth here on what the right way to solve this is...

**Comment by jeffbcross** [comment] 2016-06-25 00:37
@davideast can you ask around about this?

**Comment by quentinchap** [comment] 2016-06-25 16:11
signInWithRedirect seems to have the same issue than signInWithPopup()

**Comment by quentinchap** [comment] 2016-06-25 17:12
Same issue with credential method and cordova-plugin-facebook4 (http://stackoverflow.com/questions/37768313/using-firebase-auth-with-facebook)

`      if (this.platform.is('ios') || this.platform.is('android')) {

        Facebook.login(['public_profile']).then(function (result) {

          console.log("Facebook success: " + JSON.stringify(result));
           authGlob.login(result.authResponse.accessToken, { provider: AuthProviders.Facebook })
            .then((success) => {
              console.log("Firebase success: " + JSON.stringify(success));
            })
            .catch((error) => {
              console.log("Firebase failure: " + JSON.stringify(error));
            });
        })`

**Comment by quentinchap** [comment] 2016-06-26 00:16
After some correction I find a work around. I propose some add to the documentation #287

**Comment by jlsuarezs** [comment] 2016-07-08 01:16
Any way to make it work?
Thank you.

**Comment by ciekawy** [comment] 2016-07-08 13:27
looks like some PR is needed for either firebase 3 or angularfire2. also seems that the difficulty now is to specify the area of responsibility which is now a pingpong between firebase, angularfire2 and also the ionic. Actually I'm little confused which is (and if there is any) github repo for JS firebase 3 as firebase package on npmjs.com points to firebase.google.com

So as a first step it would be great to have clear if it is acceptable that i.e. file:// protocol is supposed to be handled, and then if the patch is required on the firebase or angularfire2. 

Any suggestions or even better PRs will be very valuable.

**Comment by ciekawy** [comment] 2016-07-08 13:36
does it make sense to add some `Help Wanted!` or other label to raise the importance/severity? looks like this is actually a blocker for ionic/phonegap apps.

**Comment by jlsuarezs** [comment] 2016-07-11 04:13
Yes, you're right.

Any news about this?

**Comment by Chuckv01** [comment] 2016-07-11 14:36
I haven't seen any activity on this in awhile. I don't know if cordova support is a priority for the angularfire team at this point.

**Comment by ciekawy** [comment] 2016-07-11 14:55
I guess that it's not about the cordova but about a use case of app loaded from file - there is rather no reason why it should not be supported. And also this was working with firebase 2 (togheter with i.e. https://github.com/ciekawy/angular2-firebase) so this is kind of regression for people moving to new recommended firebase 3 SDK

**Comment by Lindstrom1989** [comment] 2016-07-11 15:12
Since upgrading to firebase 3 in my ionic app I have had many major breaking issues I'm about a month behind :( are there any temporary fixes?

**Comment by cnothegger** [comment] 2016-07-12 14:28
I don't know who is developing AngularFire2 but the problem is on the Firebase side.

I contact the Firebase team and this the answer:
Are you using popup / redirect sign in methods in Firebase 3.x.x? If so, these methods are currently not supported in native Ionic/Cordova apps. Sorry about that. 
As a workaround, I recommend to use a library for OAuth such as ngCordova(in Cordova and Ionic apps) and then use auth().signInWithCredential(...) to sign your users in.

**Comment by Lindstrom1989** [comment] 2016-07-13 11:58
@cnothegger Could you elaborate on the fix, I don't understand how using sign in with credentials can login oauth firebase users. Is this something thats needs to be pushed to ionic to fix? thanks

**Comment by aaronksaunders** [comment] 2016-07-13 12:03
I think this thread is mixing issues, you can login to firebase using a plugin to get the oauth credentials and pass them through. Yes it is as neatly integrated in to angular fire, but there is a work around

**Comment by jlsuarezs** [comment] 2016-07-14 02:01
Solved using Firebase only.

Check this:
Advanced: Handle the sign-in flow manually
https://firebase.google.com/docs/auth/web/facebook-login

**Comment by jgw96** [comment] 2016-07-15 22:34
This seems to be fixed in a cordova environment (specifically Ionic 2) with `angularFire2@next` but i can't seem to get any auth information. If you subscribe to AngularFire.auth() it never actually fires when the user logs in. Works fine in Chrome. Im guessing this issue is related to this line https://github.com/angular/angularfire2/blob/master/src/auth/auth.ts#L45. Unfortunately that looks like the line that fixed `auth.login()` not working.

**Comment by aaronksaunders** [comment] 2016-07-16 03:11
@Lindstrom1989 @jgw96 This solution using [ionic-native facebook plugin](http://ionicframework.com/docs/v2/native/facebook/) to get the accessToken, creates the credential and then successfully logs in using angularFire2
  https://github.com/aaronksaunders/basicaf2

**Comment by nelsonad** [comment] 2016-07-21 17:58
@aaronksaunders Thank you for the complete working project! 

I kept getting typescript build errors til I saw your `declare var firebase: any` trick.

**Comment by mateusmcg** [comment] 2016-07-24 02:07
@aaronksaunders thanks for the solution, but there is a way to use angularfire2 auth with google?

In my project here we dont use facebook auth...

**Comment by Chuckv01** [comment] 2016-07-24 02:10
@mateusmcg I believe you can use the Google Plus plugin for Google oAuth then pass the token to FB the same way: http://ionicframework.com/docs/v2/native/google-plus/

**Comment by mateusmcg** [comment] 2016-07-24 03:02
@Chuckv01 thx for the quick reply.

I was not able to make [this](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) plugin working with ionic 2. I've only found examples that uses angular 1 not angular 2, so i was not able to import the right module to get the plugin to work.

If someone manage to get ionic2 working with angularfire2/firebase google auth and could post a little piece of code, i would appreciate it

**Comment by gauravk92** [comment] 2016-07-27 19:55
We ended up using this code:

https://github.com/timdream/google-oauth2-web-client/blob/master/src/google-oauth2.js

To throw the popup and handle auth manually to get the access token. At which point we pass to firebase like so (after validation of the token at: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=)

    const googleConfig = {
      method: AuthMethods.OAuthToken,
      provider: AuthProviders.Google
    };
    const creds = (firebase.auth.GoogleAuthProvider as any).credential(null, token);
    this.af.auth.login(creds, googleConfig)

**Comment by ciekawy** [comment] 2016-07-27 20:30
also here similat approach using plugins for facebook and google and also pure web google login option
https://github.com/rodrigoreal/ionic2-angularfire-login

**Comment by srikantk** [comment] 2016-08-10 09:03
I found a quicker approach, used authwithredirect apis from firebase and local-webserver plugin from cordova it mostly works.

**Comment by nunoarruda** [comment] 2016-08-10 17:05
Still an issue even with `npm install angularfire2@next --save`:

![img_1369](https://cloud.githubusercontent.com/assets/1189149/17562905/43988656-5f2d-11e6-8122-39c11ddb38f8.PNG)

**Comment by RubnC** [comment] 2016-08-19 10:35
Some news? 
For me it's working fine on Chrome but not on android neither ios.

**Comment by katowulf** [comment] 2016-09-01 18:32
Since this is an issue with the Firebase Authentication SDK, and not related to the AngularFire2 project, the best workaround will continue to be using native auth methods and redirect, as @ciekawy and @gauravk92 have illustrated.

**Closed** 2016-10-26 12:09 UTC
Labels: comp: auth, type: bug

**Comment by richarddiogo** [comment] 2016-10-31 19:19
Some news?

**Comment by valterh4ck3r** [comment] 2017-01-20 02:03
Some news?

**Comment by codeFire97** [comment] 2017-01-24 13:35
some news?

**Comment by valterh4ck3r** [comment] 2017-01-24 17:31
I sent a email from support firebase,

They answer me with the email : 


> When you're building an ionic/cordova app (or any app that is running in an environment outside of a browser), then using any of these operations: signInWithPopup(), signInWithRedirect(), linkWithPopup(), and linkWithRedirect() will not work because they do not have a real domain name. Currently the solution to this is to use an OAuth library and then use signInWithCredential(). You can view a similar example here for implementing twitter login.
> 
> Hope that helps.
> 
> Best Regards,
> Aye

I can't implement signInWithCredential with google, then i used the facebook auth for my app... This is my workaround...

**Comment by codeFire97** [comment] 2017-01-24 17:37
https://market.ionic.io/starters/firebase-v3-auth-social-kit-2
This solved my problem completely

**Comment by valterh4ck3r** [comment] 2017-01-24 22:23
15$ ?

He uses in-app-browser, with option _system  browser, this solution is a javascript approach, don't work in native view...

See about : https://ionicthemes.com/tutorials/about/native-facebook-login-with-ionic-framework

**Comment by diegobdev** [comment] 2017-01-27 18:33
I work with Ionic 2.2, Cordova 6.5 and Firebase v3 and have same error using "let provider = new firebase.auth.GoogleAuthProvider();
    firebase.auth().signInWithPopup(provider)" or "let provider = new firebase.auth.FacebookAuthProvider();
    return firebase.auth().signInWithPopup(provider)" :
Error: {"code":"auth/operation-not-supported-in-this-environment","message":"This operation is not supported in the environment this application is running on. \"location.protocol\" must be http or https and web storage must be enabled."}

**Comment by richarddiogo** [comment] 2017-01-27 18:45
15 $? so hard ;s

I will try :" I can't implement signInWithCredential with google, then i
used the facebook auth for my app... This is my workaround."





2017-01-27 16:33 GMT-02:00 Diego Borges (diegobdev) <
notifications@github.com>:

**Comment by alheranx** [comment] 2017-02-06 18:12
> https://market.ionic.io/starters/firebase-v3-auth-social-kit-2
This solved my problem completely

what enviroment do you use?.  In the comments sections the author says it not works in ionic view.

**Comment by vkniazeu** [comment] 2017-03-14 15:32
@alheranx, I've just tried that demo app within Ionic View and indeed neither FB nor Google login works.
Perhaps, they will work in a standalone iOS and/or Android builds on devices or within emulators, but trying is time intensive.
Have a solution that would work within Ionic View would be a time saver for testing.

**Comment by rainabba** [comment] 2017-04-17 18:38
I'm seeing this in QtWeb 3.8.5. It can't even run Gmail, lacks ES6 support (I use Babel to translate to ES5 code), is the same JS engine in the WkhtmlToPdf project (which is HUGELY popular project for converting pages to PDF in a well controlled/formatted manner).

**Comment by dpassis** [comment] 2017-06-24 16:16
Solution: the issue was corrected in the latest Firebase JavaScript SDK release (4.1.3)

[Firebase JavaScript SDK Release Notes](https://firebase.google.com/support/release-notes/js#4.1.3)

**Comment by edzillion** [comment] 2017-06-24 18:45
@dpassis have you tested it? I haven't been following this issue closely so maybe I am doing something wrong. This works on browser:

`
    this.userService.auth.signInWithPopup(new firebase.auth.FacebookAuthProvider())
    .then(
      (success) => {
        console.log('fb auth success');
        this.loading.dismiss();
      }).catch(
      (err) => {
        console.error(err);
      });
`
I get:
`
code: "auth/operation-not-supported-in-this-environment"
message: "This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled."
`

I am not building _without_ the --prod flag on ionic:

`
global packages:                                                      
                                                                      
    @ionic/cli-utils : 1.4.0                                          
    Cordova CLI      : 7.0.1                                          
    Ionic CLI        : 3.4.0                                          
                                                                      
local packages:                                                       
                                                                      
    @ionic/app-scripts              : 1.3.8                           
    @ionic/cli-plugin-cordova       : 1.4.0                           
    @ionic/cli-plugin-ionic-angular : 1.3.1                           
    Cordova Platforms               : android 6.2.3 browser 4.1.0     
    Ionic Framework                 : ionic-angular 3.4.2             
                                                                      
System:                                                               
                                                                      
    Node       : v6.11.0                                              
    OS         : Windows 8.1                                          
    Xcode      : not installed                                        
    ios-deploy : not installed                                        
    ios-sim    : not installed                                        
    npm        : 4.1.2                                                
`

package.json:
`
"angularfire2": "^4.0.0-rc.1",
"firebase": "^4.1.3",
`

**Comment by dpassis** [comment] 2017-06-24 19:34
@edzillion the method signInWithPopup don't work with cordova/ionic, you should use the signInWithRedirect method.

**Comment by mateusmcg** [comment] 2017-06-25 00:42
@dpassis Thanks for the follow up.

I'm running: 

- Firebase 4.1.3:
- angularfire2: 4.0.0-rc.1
- ionic-angular: 3.3.0
- angular: 4.1.2

And i tried the following code in a Android Device with both Google and Facebook providers.

```
this.afAuth.auth.signInWithRedirect(new firebase.auth.GoogleAuthProvider()).then(result => {
        console.debug(result);
        alert("Success");
      }, error => {
        console.debug(error);
        alert("Failed - " + error.message);
      });
```

But i keep getting the error:

"This domain (my ip address) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab"

I already have "localhost" and "my app name" added to the list of domains by default. Doesn't make sense to me that i have to add my ip address to that list. But i tried anyway and still failed.

This might be a silly problem to solve but i'm kinda lost.

Any idea what i'm doing wrong?

**Comment by dpassis** [comment] 2017-06-25 01:16
@mateusmcg make sure that all windows are open by inappbrowser 
Something like that: 
 function onDeviceReady() {
            window.open = cordova.InAppBrowser.open;
        }

Also make sure that all configs listed in the tutorial are done.
[](https://firebase.google.com/docs/auth/web/cordova)

**Comment by mateusmcg** [comment] 2017-06-25 01:54
@dpassis Thanks for the quick response

After removing "--livereload" from the command `ionic cordova run android` i started to get a few errors asking to install a few cordova plugins, which are:

- cordova-plugin-browsertab
- cordova-plugin-buildinfo
- cordova-universal-links-plugin
- cordova-plugin-inappbrowser

After installing these plugins the google auth page opened normally. 

And after chosing my Google Account i'm sent back to the app. But i get no user authenticated within firebase (The promise below returns null):

```
getAuthenticatedUser() {
    return this.afAuth.authState;
  }
```

I had to configure a Dynamic Link and a SHA-1 key in the firebase console to get the Google OAuth page to open. Maybe i did something wrong there?

Any idea how to get the authenticated user after selecting the google account and redirecting back to the app?

**Comment by dpassis** [comment] 2017-06-25 02:24
@mateusmcg 
1)You need create in the firebase console a android app and add the same id below:
<widget **id="com.app"** version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">

2)You need create a new  dynamic link and relate that with your android app created in the step **1**,
so in the config.xml

  <universal-links>
        <host name=**"the link created in the step 2"** scheme="https" />
        <host name=**"https://yourapp.firebaseapp.com"** scheme="https">
            <path url="/__/auth/callback" />
        </host>
    </universal-links>

p.s.: host name is your **authDomain**, get this in your firebase snnipet

**Comment by mateusmcg** [comment] 2017-06-25 03:35
@dpassis The app is created in firebase and tried to added the universal-links section in the config.xml file like below:

```
...
<universal-links>
        <host name="https://<my Dynamic Link>" scheme="https" />
        <host name="https://myApp.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
</universal-links>
...
```

But the behavior stayed the same. 

Using the code below the success promise is not triggered, instead when i select the google account the app "refreshes" (like opening for the first time) and i get no firebase user authenticated.

```
this.afAuth.auth.signInWithRedirect(new firebase.auth.GoogleAuthProvider()).then(result => {
        console.debug(result);
        alert("Success");
      }, error => {
        console.debug(error);
        alert("Error");
      });
```

I think the expected behavior should be the user being redirect back to the app (instead the app reloading entirely again) and that success promise triggered with the authenticated user. Am i doing something wrong here?

**Comment by fluentwait** [comment] 2017-07-16 09:53
https://javebratt.com/ionic-social-login-firebase/ 
Follow this guide...It worked for me

**Comment by renanss** [comment] 2017-07-18 02:42
@fluentwait it worked :)

**Comment by feliperfmarques** [comment] 2017-12-20 21:11
I followed this guide indicated by @fluentwait, in addition to this:

https://firebase.google.com/docs/auth/web/cordova?hl=en-us

**Comment by bogacg** [comment] 2018-01-13 09:16
When I add `<univesal-links>` tag in `config.xml` I'm getting this error:
>Cannot read property 'manifest' of undefined.
Din't you guys get that error to start with ?

**Comment by alkahtani** [comment] 2018-03-21 21:24
https://javebratt.com/ionic-social-login-firebase/
Follow this guide...It worked for me

**Comment by ToothpickFactory** [comment] 2018-04-29 18:57
When I switched to
`
import { firebase } from '@firebase/app';

// import these as needed..
import '@firebase/auth'; 
import '@firebase/database'; 
import '@firebase/firestore';
`

It worked

**Comment by alkahtani** [comment] 2018-05-30 08:56
this artical solved the issue , follow up and let us know.

[Ionic Social login ](https://javebratt.com/ionic-social-login-firebase/)
