### ISSUE TITLE
How can I retrieve images after upload in storage angularfire2 then stored in angularfiredatabase?

### ISSUE THREAD

**Issue by Omar-Qalei** [angular/angularfire2#1781] opened 2018-07-18 15:16 UTC
How can I retrieve images after upload in storage angularfire2 then stored in angularfiredatabase?

I can see links   in console but can't show that in ngfor html 
console : 
itemList{
...//another data
...//another data
...//another data
multiImages {
0: "URL image",
1: "URL image",
2: "URL image",
3: "URL image",
4: "URL image",
 }
}

**Comment by Steven-Harris** [comment] 2018-07-19 06:05
Please refer to the [docs](https://github.com/angular/angularfire2/blob/master/docs/storage/storage.md)
Specifically, if you save the image path available you can use .getDownloadURL() to get the full image url

**Comment by FiringBlanks** [comment] 2018-07-29 10:45
This question is better asked on StackOverflow. But since you asked: 

```
//Create a random (unique) UID for file to use in Firestore and Storage
let fileID = this.afs.createId();

//Set path for Firestore upload
var firestorePath = 'C1/D1/P2/' + fileID
const storagePath = "/Uploads/" + fileID;

//Actually upload file to Firestore now
const storageRef: firebase.storage.Reference = firebase.storage().ref(storagePath);
const uploadTask: firebase.storage.UploadTask = storageRef.put(firestorePath);

//After uploading the file
uploadTask.then((uploadSnapshot: firebase.storage.UploadTaskSnapshot) => {
    
    //Fetch the download URL of the Storage file
    uploadSnapshot.ref.getDownloadURL().then((downloadURL) => {

        //Now create the Firestore entry
        this.afs.doc(path).set({
            FileName: uploadSnapshot.metadata.name,
            FileContentType: uploadSnapshot.metadata.contentType,
            FileSize: uploadSnapshot.metadata.size,
            FileURL: downloadURL,
            FileTimeCreated: uploadSnapshot.metadata.timeCreated,
        })
    }
})
```

**Comment by Omar-Qalei** [comment] 2018-07-29 13:10
I solved this problem last 2 weeks ago. 👍 using file reader and for loop.
 thanks for help.

**Comment by FiringBlanks** [comment] 2018-07-29 22:07
If the issue is solved, please close it.

**Closed** 2018-07-30 18:11 UTC

**Comment by rsRamgharia** [comment] 2019-01-31 10:47
Thanku my problem solved...

**Comment by bhargav05** [comment] 2019-05-01 12:38
how can access angular firebase storage to upload file???

**Comment by bhargav05** [comment] 2019-05-01 12:38
core.js:1673 ERROR Error: Uncaught (in promise): FirebaseStorageError: {"code_":"storage/unauthorized","message_":"Firebase Storage: User does not have permission to access '190pc2nasnp'.","serverResponse_":"{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Permission denied. Could not perform this operation\"\n  }\n}","name_":"FirebaseError"}

**Comment by Omar-Qalei** [comment] 2019-05-01 14:00
> core.js:1673 ERROR Error: Uncaught (in promise): FirebaseStorageError: {"code_":"storage/unauthorized","message_":"Firebase Storage: User does not have permission to access '190pc2nasnp'.","serverResponse_":"{\n "error": {\n "code": 403,\n "message": "Permission denied. Could not perform this operation"\n }\n}","name_":"FirebaseError"}

Check firebase storage rules

**Comment by VickyMutai** [comment] 2019-05-07 12:38
> core.js:1673 ERROR Error: Uncaught (in promise): FirebaseStorageError: {"code_":"storage/unauthorized","message_":"Firebase Storage: User does not have permission to access '190pc2nasnp'.","serverResponse_":"{\n "error": {\n "code": 403,\n "message": "Permission denied. Could not perform this operation"\n }\n}","name_":"FirebaseError"}

Kindly ensure user has logged in. That is an authentication error

**Comment by Acewill90** [comment] 2019-10-22 15:27
> I solved this problem last 2 weeks ago. 👍 using file reader and for loop.
> thanks for help.

Can you put the code here pls,
Thank you

**Comment by Omar-Qalei** [comment] 2019-10-22 16:07
uploadMultiImage(event) {


    const files = event.target.files;
    for (const file of files) {
      const id = Math.random().toString(36).substring(2);
      const reader = new FileReader();
      reader.onload = (e: any) => {
        const task = this.storage.upload(id, file).then(() => {
          const ref = this.storage.ref(id);
          const downloadURL = ref.getDownloadURL().subscribe(url => {
            this.dataAdd.multiImage.push(url);
          });
          this.percentageMultiImage = this.storage.upload(id, file).percentageChanges();
        });
      };
      reader.readAsDataURL(file);
    }

  }

**Comment by Acewill90** [comment] 2019-10-22 16:29
thank you, i will check it, but in vue.js so i have to transform the code a little bit

**Comment by Acewill90** [comment] 2019-10-23 12:14
@Omar-Qalei thanks very much for the idea, it works ;)
