### ISSUE TITLE
af.auth.subscribe()  double notifications with 'redirect'  sign-in

### ISSUE THREAD

**Issue by lawipac** [angular/angularfire2#452] opened 2016-08-19 19:04 UTC
auth.subscribe() will produce two state changes after successfully redirect back from google login
1. valid user object
2. null.  (which I think is unnecessary) <<<=================

**to reproduce this:**

1. create project using ng new
2. replace app.component.ts with 

```
import { Component, OnInit } from '@angular/core';
import { AngularFire, FirebaseAuthState } from 'angularfire2';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  template: `
<div> {{ (af.auth | async)?.uid }} </div>
<button (click)="login()">Login</button>
`,
  styleUrls: ['app.component.css']
})
export class AppComponent {
  title = 'app works!';
  constructor(public af: AngularFire) {
    af.auth.subscribe((user:FirebaseAuthState) => this.onUserStateChange(user));
  }

  login() {
    this.af.auth.login();
  }

  onUserStateChange(user: FirebaseAuthState) {
      console.log("user state changed " + user);
  }
}
```

**then:**  main.ts is using  'redirect' for login ( if using popup, this program works flawlessly)

```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { 
  defaultFirebase, 
  FIREBASE_PROVIDERS,
  AngularFire, 
  AuthMethods, 
  AuthProviders, 
  firebaseAuthConfig  
  } from 'angularfire2';
if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent,[
  FIREBASE_PROVIDERS,
  defaultFirebase({
    apiKey: "-------to be replaced with firebase------",
    authDomain: "-------------",
    databaseURL: "https://---------",
    storageBucket: "-----------",
  }),
  firebaseAuthConfig({
    provider: AuthProviders.Google,
    method: AuthMethods.Redirect
  })
]);
```

Console will log two state changes after successfuly redirect back from google login
1. valid user object
2. null.  (which I think is unnecessary) <<<=================

**Comment by davideast** [comment] 2016-08-19 21:32
Dupe of #413. Fixing in the next release.

**Closed by davideast** 2016-08-19 21:32 UTC
