### ISSUE TITLE
Upgrade to firebase 3.4.1 causes Cannot read property 'FacebookAuthProvider'

### ISSUE THREAD

**Issue by seanmavley** [angular/angularfire2#587] opened 2016-10-04 10:00 UTC
Upgrade to firebase 3.4.1 causes the 'Cannot read property 'FacebookAuthProvider'. I am not using Facebook Auth anywhere in my project, so my code isn't the culprit.

Rollback to Firebase 3.4.0 fixes the issue.

Specs:
Firebase 3.4.1 (breaks)
AngularFire 2.0.0-beta.5
Angular 2.0.1

I'm not using Angular-CLI. Setup can be found here: https://github.com/seanmavley/AngularFire2-Authentication

![screenshot from 2016-10-04 09-55-53](https://cloud.githubusercontent.com/assets/5289083/19070050/016b23b2-8a19-11e6-9db7-08caeb39c4d9.png)

**Comment by mukesh51** [comment] 2016-10-04 11:18
Duplicate of Issue #576

**Closed** 2016-10-04 21:58 UTC
