### ISSUE TITLE
Support Angular 4

### ISSUE THREAD

**Issue by eliotstock** [angular/angularfire2#887] opened 2017-04-05 10:02 UTC
Angular: 4.0.1
Firebase: 3.7.5
AngularFire: 2.0.0-beta.8

Steps to repro:

```
$ npm install -g @angular/cli
$ ng new foo
$ cd foo
$ npm install firebase angularfire2 --save

foo@0.0.0 /Users/eliot/dev/foo
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.1
├── angularfire2@2.0.0-beta.8 
└─┬ firebase@3.7.5 
  ├── base64-url@1.3.3 
  ├── base64url@2.0.0 
  ├── buffer-equal-constant-time@1.0.1 
  ├── dom-storage@2.0.2 
  ├── ecdsa-sig-formatter@1.0.7 
  ├── faye-websocket@0.9.3 
  ├── hoek@2.16.3 
  ├── isemail@1.2.0 
  ├── joi@6.10.1 
  ├── jsonwebtoken@7.1.9 
  ├── jwa@1.1.4 
  ├── jws@3.1.4 
  ├── lodash.once@4.1.1 
  ├── moment@2.16.0 
  ├── ms@0.7.2 
  ├── rsvp@3.2.1 
  ├── safe-buffer@5.0.1 
  ├── topo@1.1.0 
  ├── websocket-driver@0.6.5 
  ├── websocket-extensions@0.1.1 
  ├── xmlhttprequest@1.8.0 
  └── xtend@4.0.1 

npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.8 requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.
```

**Comment by davideast** [comment] 2017-04-05 11:54
Duplicate of #843.

**Closed by davideast** 2017-04-05 11:54 UTC

**Comment by eliotstock** [comment] 2017-04-05 12:33
Sorry, how is this a duplicate of that? I'm not seeing the same errors mentioned in that issue. Do you mean that, once #843 is fixed, it'll be trivial to support Angular 4?

**Comment by davideast** [comment] 2017-04-05 12:37
I want to have only one issue for Angular 4 support. OpaqueToken to InjectToken is also Angular 4 support related. Now this issue will be references in the UI in the main issue.

Also, out of curiosity, have you tried running the app? Those errors are from npm and not from anything at compile or runtime.

**Comment by eliotstock** [comment] 2017-04-05 15:48
Got it, cool. Yeah it runs OK so far, but creates uncertainty and doubt that something might be broken of which I'm not aware.

**Comment by zero19** [comment] 2017-04-06 05:29
Is there a temporary fix for this?

**Comment by jakehockey10** [comment] 2017-04-12 00:43
Mine runs *locally* just fine, but during a Travis CI build, it fails due to build:
```
ERROR in Error encountered resolving symbol values statically. 
Calling function 'OpaqueToken', function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function, 
resolving symbol FirebaseUserConfig in /home/travis/build/[...]/[...]/node_modules/angularfire2/tokens.d.ts, 
resolving symbol AngularFireModule.initializeApp in /home/travis/build/[...]/[...]/node_modules/angularfire2/angularfire2.d.ts, 
resolving symbol AppModule in /home/travis/build/[...]/[...]/src/app/app.module.ts, 
resolving symbol AppModule in /home/travis/build/[...]/[...]/src/app/app.module.ts
```
Therefore I can't release.

**Comment by scottmotion** [comment] 2017-04-22 04:10
Any changes on this? Just ran into the same dependency issue after updating Ionic with Angular4, Angular CLI 1.0.0 and AngularFire2 2.0.0-beta.8

$ ionic serve to Chrome works as expected but opening in the Ionic View app lags about 30 seconds on initial load. Have not tested a build or emulator otherwise

Not sure if is applies but looking over my packages.json I see this dependency has been removed as of v4:
"@angular/platform-server": "2.4.8",

**Comment by markgoho** [comment] 2017-04-22 12:23
@scottmotion `npm install angularfire2@next` -- you'll need to do some refactoring of your code, but a few of us have upgraded and are not experiencing this conflict anymore.

**Comment by scottmotion** [comment] 2017-04-22 16:42
@markgoho Thanks for the tip! I was able to find the discussion under https://github.com/angular/angularfire2/issues/854
