### ISSUE TITLE
Duplicate Identifier Errors

### ISSUE THREAD

**Issue by JimTheMan** [angular/angularfire2#707] opened 2016-12-01 22:46 UTC
### Version info

**Angular:**
angular-cli: 1.0.0-beta.20-4
node: 6.7.0
os: darwin x64
angular library: 2.1.0

**Firebase:**
3.6.2

**AngularFire:**
2.0.0-beta.6
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions
run this project, (npm i and ng serve):
https://github.com/JimTheMan/Jims-Ngrx-Example

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
Errors appear in console every time I run ng serve

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** NG Live Development Server is running on http://localhost:4200. **
14188ms building modules                5ms add03710ms 372ms asse101ms emittinggHash: 5c5a5b6ec8a2600c7776
Version: webpack 2.1.0-beta.25
Time: 19610ms
           Asset       Size  Chunks             Chunk Names
  main.bundle.js    3.74 MB    0, 2  [emitted]  main
styles.bundle.js    10.3 kB    1, 2  [emitted]  styles
inline.bundle.js    5.53 kB       2  [emitted]  inline
        main.map    4.09 MB    0, 2  [emitted]  main
      styles.map    14.2 kB    1, 2  [emitted]  styles
      inline.map     5.6 kB       2  [emitted]  inline
      index.html  484 bytes          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0       
webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:12:9 
    Duplicate identifier 'Promise'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:17:9 
    Duplicate identifier 'Promise_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:130:9 
    Duplicate identifier 'EmailAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:135:9 
    Duplicate identifier 'EmailAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:144:9 
    Duplicate identifier 'FacebookAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:148:9 
    Duplicate identifier 'FacebookAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:153:9 
    Duplicate identifier 'GithubAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:157:9 
    Duplicate identifier 'GithubAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:162:9 
    Duplicate identifier 'GoogleAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:167:9 
    Duplicate identifier 'GoogleAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:172:9 
    Duplicate identifier 'TwitterAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:177:9 
    Duplicate identifier 'TwitterAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:181:8 
    Duplicate identifier 'UserCredential'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:339:8 
    Duplicate identifier 'StringFormat'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:340:7 
    Duplicate identifier 'StringFormat'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:347:8 
    Duplicate identifier 'TaskEvent'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:348:7 
    Duplicate identifier 'TaskEvent'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:352:8 
    Duplicate identifier 'TaskState'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:353:7 
    Duplicate identifier 'TaskState'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:390:3 
    Duplicate identifier 'export='.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:12:9 
    Duplicate identifier 'Promise'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:17:9 
    Duplicate identifier 'Promise_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:132:9 
    Duplicate identifier 'EmailAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:137:9 
    Duplicate identifier 'EmailAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:146:9 
    Duplicate identifier 'FacebookAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:150:9 
    Duplicate identifier 'FacebookAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:156:9 
    Duplicate identifier 'GithubAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:160:9 
    Duplicate identifier 'GithubAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:166:9 
    Duplicate identifier 'GoogleAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:171:9 
    Duplicate identifier 'GoogleAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:177:9 
    Duplicate identifier 'TwitterAuthProvider'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:182:9 
    Duplicate identifier 'TwitterAuthProvider_Instance'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:187:8 
    Duplicate identifier 'UserCredential'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:358:8 
    Duplicate identifier 'StringFormat'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:359:7 
    Duplicate identifier 'StringFormat'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:366:8 
    Duplicate identifier 'TaskEvent'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:367:7 
    Duplicate identifier 'TaskEvent'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:371:8 
    Duplicate identifier 'TaskState'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:372:7 
    Duplicate identifier 'TaskState'.
[default] /Users/jim/git2/Jims-Ngrx-Example/jims-ngrx-eg/node_modules/firebase/firebase.d.ts:409:3 
    Duplicate identifier 'export='.
[default] Checking finished with 40 errors

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

clean run of ng serve with no errors.

**Comment by cartant** [comment] 2016-12-02 01:41
You have two `firebase` modules installed:

* `.../jims-ngrx-eg/node_modules/angularfire2/node_modules/firebase`
* `.../jims-ngrx-eg/node_modules/firebase`

Delete the first one so that AngularFire2 uses the `firebase` module that [you have specified](https://github.com/JimTheMan/Jims-Ngrx-Example/blob/master/jims-ngrx-eg/package.json#L28) in your `package.json` as a peer (see [#681](https://github.com/angular/angularfire2/pull/681)).

**Comment by zakdances** [comment] 2016-12-02 10:00
Why is `node_modules/angularfire2/node_modules` being installed?

**Comment by Chris1308** [comment] 2016-12-02 10:12
Another solution is to install firebase 3.3.0, the version of angularfire.

**Comment by cartant** [comment] 2016-12-02 10:51
@zakdances It's installed there because AngularFire2 has it as a [dependency](https://github.com/angular/angularfire2/blob/2.0.0-beta.6/package.json#L43), rather than a peer dependency. It really should be the latter. You've specified [a different version](https://github.com/JimTheMan/Jims-Ngrx-Example/blob/master/jims-ngrx-eg/package.json#L28) of Firebase, so you end up with two installations in the `node_modules` hierarchy, etc.

This wouldn't be a problem if the versions were the same. My understanding is that AngularFire2 is not using the latest version of Firebase, as there are problems with SystemJS (but I could have that wrong).

**Comment by JimTheMan** [comment] 2016-12-02 15:05
Hi. Thanks for answering guys. I'll try this. The thing is that I had firebase 3.X installed already because I was doing most of my calls with that, but then i wanted to move to ngrx/store and wanted the observables from AngularFire2. I suspect other people will come across this as well. I'm sure there is some solution where we don't have to delete a node_modules folder. :)

**Comment by thegrid22593** [comment] 2016-12-04 00:16
Hi everyone,

I am having the same issue minus the node_modules being in the angularfire2 folder...

Not sure exaclty what is going since I am pretty new to using angularfire and firebase.

Here is my console error....

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(12,9): error TS2300: Duplicate identifier 'Promise'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(100,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'currentUser' must be of type 'any', but here has type 'User'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(130,9): error TS2300: Duplicate identifier 'EmailAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(144,9): error TS2300: Duplicate identifier 'FacebookAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(153,9): error TS2300: Duplicate identifier 'GithubAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(162,9): error TS2300: Duplicate identifier 'GoogleAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(172,9): error TS2300: Duplicate identifier 'TwitterAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(181,8): error TS2300: Duplicate identifier 'UserCredential'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(196,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(253,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'key' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(321,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cacheControl' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(321,5): error TS2687: All declarations of 'cacheControl' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(322,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'contentDisposition' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(322,5): error TS2687: All declarations of 'contentDisposition' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(323,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'contentEncoding' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(323,5): error TS2687: All declarations of 'contentEncoding' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(324,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'contentLanguage' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(324,5): error TS2687: All declarations of 'contentLanguage' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(325,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'contentType' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(325,5): error TS2687: All declarations of 'contentType' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(326,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'customMetadata' must be of type 'any', but here has type '{ [key: string]: string; }'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(326,5): error TS2687: All declarations of 'customMetadata' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(347,8): error TS2300: Duplicate identifier 'TaskEvent'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(348,7): error TS2300: Duplicate identifier 'TaskEvent'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(352,8): error TS2300: Duplicate identifier 'TaskState'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(353,7): error TS2300: Duplicate identifier 'TaskState'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(362,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'md5Hash' must be of type 'any', but here has type 'string'.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(362,5): error TS2687: All declarations of 'md5Hash' must have identical modifiers.

ERROR in /Users/Garrett/Development/aabc-check-off/node_modules/firebase/firebase.d.ts
(390,3): error TS2300: Duplicate identifier 'export='.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(56,11): error TS2300: Duplicate identifier 'Promise'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(183,28): error TS2300: Duplicate identifier 'Promise'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(700,11): error TS2300: Duplicate identifier 'FacebookAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(727,11): error TS2300: Duplicate identifier 'GithubAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(754,11): error TS2300: Duplicate identifier 'GoogleAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(784,11): error TS2300: Duplicate identifier 'TwitterAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(807,11): error TS2300: Duplicate identifier 'EmailAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(838,15): error TS2300: Duplicate identifier 'UserCredential'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1233,33): error TS2300: Duplicate identifier 'FacebookAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1239,33): error TS2300: Duplicate identifier 'GithubAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1245,33): error TS2300: Duplicate identifier 'GoogleAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1251,33): error TS2300: Duplicate identifier 'TwitterAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1257,33): error TS2300: Duplicate identifier 'EmailAuthProvider'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(1678,15): error TS2320: Interface 'ThenableReference' cannot simultaneously extend types 'Thenable<void>' and 'Thenable<any>'.
  Named property 'then' of types 'Thenable<void>' and 'Thenable<any>' are not identical.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(2407,10): error TS2300: Duplicate identifier 'TaskEvent'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(2413,10): error TS2300: Duplicate identifier 'TaskState'.

ERROR in /Users/Garrett/Development/aabc-check-off/typings/globals/firebase/index.d.ts
(2441,5): error TS2300: Duplicate identifier 'export='.

**Comment by thegrid22593** [comment] 2016-12-04 00:22
Hi All,

Just found the solution here... http://stackoverflow.com/questions/40506657/duplicate-identifier-while-using-firebase-in-angular2

If you go into the firebase directory in your node_modules folder you will see an app.d.ts and a firebase.d.ts. Both of these files contain the same definitions which cause the duplicate error. Delete firebase.d.ts and all the errors will resolve.

This worked for me. Hopefully this will help someone else.

**Comment by danielehrhardt** [comment] 2016-12-12 20:36
Many People have a Problem with this can you please fix it?

Thanks,
Daniel

**Comment by davideast** [comment] 2016-12-26 21:31
This should be fixed with #681. The fix is published under the `next` tag (`npm i angularfire2@next`). After a few more issues are addressed we'll do a release.

**Comment by rosslavery** [comment] 2016-12-28 18:40
Correct me if I'm wrong, but #681 doesn't actually set it as a peer dependency, it just updates the version tag, but keeps `firebase` listed inside the `dependencies` section.

This results in firebase still being installed inside the angularfire2 node_modules directory.

**Comment by davideast** [comment] 2016-12-29 14:54
@rosslavery The package is re-written in during a release to set `dependencies` to `peerDependencies`, the issue is that they are still being left as `dependencies`. I've made the change to delete them as `dependencies` on a release.

**Closed** 2017-01-13 16:50 UTC

**Comment by thetylerb** [comment] 2017-11-12 23:10
I ran into this issue because i ran firebase init when I already had angularfire2 included in my app. I solved the issue by deleting node modules, then re-installing.
