### ISSUE TITLE
[Feature] Angularfire2 transaction

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#649] opened 2016-10-29 17:38 UTC
I've been checking how I can add a value to existing value in my firebase database, and I was refered to the following:

https://firebase.google.com/docs/reference/js/firebase.database.Reference#transaction

> `transaction()`is used to modify the existing value to a new value, ensuring there are no conflicts with other clients writing to the same location at the same time.

If it does exists and can be used with angularfire2, I couldn't find anything about it in the documentation.

**Comment by mukesh51** [comment] 2016-11-01 19:14
@theunreal Did you get a chance to look at this [section](https://github.com/angular/angularfire2/blob/master/docs/api-reference.md#firebaselistobservable).

**Comment by theunreal** [comment] 2016-11-01 20:11
@mukesh51 Yes, Do you see anything about `transaction`? Because there is nothing about it.

**Comment by mukesh51** [comment] 2016-11-01 21:55
@theunreal I didn't see the transaction method, but my guess is, if it has to be available, then it has to exists in firebase_list_observable definition file. Again, my assumption is, I don't  believe angularFire2 will mimic every method of firebase API, which might not make sense.

I'll leave it to experts.
@katowulf @davideast @jeffbcross  do you guys want to weigh in here, please.

**Comment by fabien0102** [comment] 2016-11-02 13:57
@theunreal  I had transaction support in PR https://github.com/angular/angularfire2/pull/610 if want ;)

**Comment by katowulf** [comment] 2016-11-03 02:40
Duplicate of #201 

FYI - You can use it directly from the SDK. 
```
import * as firebase from 'firebase';
firebase.database().transaction(...);
```

**Closed by katowulf** 2016-11-03 02:40 UTC

**Comment by theunreal** [comment] 2016-11-12 09:10
hey @katowulf , this waht happens when i'm trying to use `import * as firebase from 'firebase';`

http://i.imgur.com/nbPQhsd.png
