### ISSUE TITLE
feat(storage): upload, read, and process* files

### ISSUE THREAD

**Issue by choopage** [angular/angularfire2#213] opened 2016-06-08 01:08 UTC
**I'm submitting a feature request.**

**Current behavior**
Exploring ways to handle file upload (images & pdf in particular) using Angular2. I was searching around the web and all the solutions points to using the multer middleware (an express app) for file upload.

**Expected/desired behavior**
The outcome I would like to achieve is to use Angular2 front end to allow user to upload the file to a Firebase3 storage as per Firebase SDK3. 

**Question**
1. Will direct file storage to Firebase Storage be a part of AngularFire2? (I believe the answer is [Yes](https://github.com/angular/angular/issues/9024))
2. If so, when will it be available?
3. The process\* in the title is referring to processing the images and documents using Google Vision API. Will AngularFire2 have inbuilt connector to perform this?

**Comment by davideast** [comment] 2016-06-09 21:14
**Answers**
1) Will direct file storage to Firebase Storage be a part of AngularFire2? 
  - Yes! 💯 

2) If so, when will it be available?
  - No date yet, but it's top on the list after the update.

3) The process* in the title is referring to processing the images and documents using Google Vision API. Will AngularFire2 have inbuilt connector to perform this?
  - This would be a feature of Firebase Storage and not AngularFire2, so I can't address it here.

**Comment by Daewju** [comment] 2016-07-21 22:05
any updates?

**Comment by choopage** [comment] 2016-08-10 04:43
Hi @davideast any updates?

**Comment by cerealexx** [comment] 2016-08-11 14:03
Hi, I'm using the regular way until it is released in AngularFire2. Just plain javascript inside a class method. But for some reason I keep getting a POST 404 error. What am I doing wrong?

This is the template: 
`<input type="file" (change)="upload($event)">`

This is the method, most of it is just a copy paste from the Firebase example:

```
upload(value){
    let file = value.target.files[0];
    let storageRef = firebase.storage().ref('noticias/' + file.name);
    let uploadTask = storageRef.put(file);
    
    uploadTask.on(firebase.storage.TaskEvent.STATE_CHANGED,
      function(snapshot) {
        // Get task progress, including the number of bytes uploaded and the total number of bytes to be uploaded
        var progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        console.log('Upload is ' + progress + '% done');
        switch (snapshot.state) {
          case firebase.storage.TaskState.PAUSED: // or 'paused'
            console.log('Upload is paused');
            break;
          case firebase.storage.TaskState.RUNNING: // or 'running'
            console.log('Upload is running');
            break;
        }
      }, function(error) {
      switch (error) {
        case 'storage/unauthorized':
          // User doesn't have permission to access the object
          break;

        case 'storage/canceled':
          // User canceled the upload
          break;

        case 'storage/unknown':
          // Unknown error occurred, inspect error.serverResponse
          break;
      }
    }, function() {
      // Upload completed successfully, now we can get the download URL
      var downloadURL = uploadTask.snapshot.downloadURL;
    });

  }
```

Any ideas?

Thx!

**Comment by escobara** [comment] 2016-08-11 17:53
Any updates on this?

**Comment by EralpB** [comment] 2016-08-17 09:30
Any updates on this?

**Comment by MMOSX** [comment] 2016-08-26 06:04
Hi, how can i upload a file on firebase storage

**Comment by davideast** [comment] 2016-08-26 12:38
@EralpB @escobara @choopage 

Right now we're focusing on some bug fixes and "recipes" section to help with common questions. After that is done we are going to start looking into Firebase Storage for AngularFire2.

**Comment by veerni** [comment] 2016-09-16 10:13
@davideast i believe this feature is not live yet, so is there a work around for the same?

**Comment by davideast** [comment] 2016-09-16 17:12
@veerni Use the regular Firebase SDK. 

https://firebase.google.com/docs/storage/web/start

**Comment by jtushar53** [comment] 2016-09-26 15:04
can i use firebase.storage() with angularfire 2, do i have to re-initialize firebase again, i have whole ionic app made up on angularfire 2, it has only one screen with file upload(profile pic).

**Comment by davideast** [comment] 2016-09-26 23:34
@jtushar53 You do not have to reinitialize if you are already using AngularFire2

**Comment by candidature** [comment] 2016-10-06 11:16
@davideast Sir we are waiting for storage API of angularfire2. Is there an update?

**Comment by okonovalenko** [comment] 2016-10-12 10:23
Any update on this feature? Thank u

**Comment by sdiazvi** [comment] 2016-10-13 17:48
any update? i'm waiting for angularfire2 storage 👍

Best regards 😃

**Comment by sunlyear** [comment] 2016-10-14 15:43
I have faced the same issue, and the current work around is to access firebaseApp (firebase instance inside AngularFire2 module). Here is the original [solution](http://stackoverflow.com/questions/39067832/accessing-firebase-storage-with-angularfire2-angular2-rc-5).

import { Component, Inject } from '@angular/core';
import { FirebaseApp } from 'angularfire2';

@Component({
  template: '<p>testing</p>'
})
export class AnyComponent {

  constructor(@Inject(FirebaseApp) firebaseApp: any) {
    const storageRef = firebaseApp.storage().ref().child('images/image.png');
    storageRef.getDownloadURL().then(url => this.image = url);
  }
}

**Comment by daslicht** [comment] 2016-10-26 07:03
Since the issue is closed I assume it has been added ? am I wrong ?

**Comment by daslicht** [comment] 2016-10-26 07:15
@sunlyear 
I just tried this solution, but  it also seams to be affected by the same bug as this:
https://github.com/angular/angularfire2/issues/637

It takes ages until the image get shown, or it it working properly for you ?

**Comment by sdiazvi** [comment] 2016-10-26 11:59
Its not ready yet, we are waiting for the final release. 

Best Regards.

**Comment by sdiazvi** [comment] 2016-10-26 15:39
Hi Mark,

Sorry but the firebase storage works really bad on the preview release, take a long time to show the files. We have to wait to the final release for better performance, because now is just 2 lines of code adapted.

Best Regards.

Sebastian Díaz Villada
Desarrollador Full-Stack
Móvil: +56 9 79852830
http://www.norweb.cl/
Antofagasta - Chile


[cid:EA86A0BA-D1E3-48FF-8230-6C7E72D06C41]


Esta comunicación puede contener material confidencial y/o información con derechos reservados del propietario, por lo tanto el uso de la misma es exclusiva para el destinatario. Si usted recibió este material por error, por favor notifíquelo inmediatamente al remitente, borre el correo y cualquier documento asociado con el mismo.

El 26-10-2016, a las 04:15, Marc Wensauer <notifications@github.com<mailto:notifications@github.com>> escribió:


@sunlyear<https://github.com/sunlyear>
I just tried this solution, but it also seams to be affected by the same bug as this:
#637<https://github.com/angular/angularfire2/issues/637>

It takes ages until the image get shown, or it it working properly for you ?

**Comment by r-vijay-r** [comment] 2016-11-01 13:49
hello this may help beginners to upload files from local drive to firebase especially for those who are using angular2 typescript angular-cli


 import { Component, EventEmitter } from '@angular/core';
import * as firebase from 'firebase';

@Component({
  selector: 'app-root',
  template: `
          <input type="file" id="filebutton" value="upload" #filebtn (change)="filebuttoni($event)">
                `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  	storageref;
  	storage;
  	path;
  constructor(){
  	let config = {
    apiKey: <try-yours>,
    authDomain: <try-yours>,
    databaseURL: <try-yours>,
    storageBucket: <try-yours>
  	};
  	firebase.initializeApp(config);
  	this.storage =firebase.storage().ref();
  }
  filebuttoni(event){
  	let files = event.srcElement.files[0];
  	let uploader=document.getElementById("uploader");
  	this.path="images/"+files.name;
  	this.storageref=this.storage.child(this.path);
  	let task=this.storageref.put(files);
  }
}



make sure you made your firebase storage rules true because i am not doing authentication since this is a test code. i got this form some great programmers written their answers in stackoverflow . i am new in this so you may get explanations from experts. i done "npm install --save angularfire2 firebase" . works for me. please let me know if i did anything wrong. thank you

**Comment by MmtBkn** [comment] 2016-11-03 03:35
Hi @davideast any updates?

**Comment by da45** [comment] 2016-12-23 15:03
Hi @davideast, 
Please any news about this  feature? please give us just an estimation of the release date,

**Comment by katowulf** [comment] 2016-12-27 19:27
Hi Folks, there are no ballparks or public release dates we can share. Sorry.

**Closed** 2017-05-04 19:01 UTC
Labels: type: feature
