### ISSUE TITLE
social sign in/up doesn't get client's email

### ISSUE THREAD

**Issue by vrs1985** [angular/angularfire2#1579] opened 2018-04-24 11:05 UTC
ver.
Angular:  5.0.2
"firebase": "4.6.2",
"angularfire2": "^5.0.0-rc.5-next"

I use signin method from docs .

const provider = new firebase.auth.FacebookAuthProvider();
OR
const provider = new firebase.auth.GoogleAuthProvider();
this.afAuth.auth.signInWithPopup(provider).then((credential) =>  {
console.log(credentials);
});

I had working code, and it returned to me email directly (example email: ***@gmail.com), but a few days ago it was broken, and now through facebook auth I can go to >>> additionalUserInfo.profile.email and retrieve email, but unfortunatelly through google auth I can't find email. this has email: null in my "credential" object that return authInfo

**Comment by jamesdaniels** [comment] 2018-05-04 20:40
Closing since not an issue with AF2, if the problem is persisting now that Facebook has done all the changes to their platform open an issue on the Firebase js sdk directly.

**Closed by jamesdaniels** 2018-05-04 20:40 UTC
