### ISSUE TITLE
Building with NGC : Can't resolve all parameters for AngularFirestore

### ISSUE THREAD

**Issue by ThomasKientz** [angular/angularfire2#1280] opened 2017-10-18 13:45 UTC
Console from `ionic build --prod` : 

```
ionic build --prod
[INFO] Running app-scripts build: --prod
       
[15:38:33]  build prod started ... 
[15:38:33]  clean started ... 
[15:38:33]  clean finished in 6 ms 
[15:38:33]  copy started ... 
[15:38:33]  deeplinks started ... 
[15:38:33]  deeplinks finished in 234 ms 
[15:38:33]  ngc started ... 
Warning: Can't resolve all parameters for AngularFirestore in /Users/thomas/Documents/Dev/Meet/Meet-Ionic/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for AngularFirestore in /Users/thomas/Documents/Dev/Meet/Meet-Ionic/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v5.x
[15:38:41]  ngc finished in 7.53 s 
[15:38:41]  preprocess started ... 
[15:38:41]  copy finished in 7.86 s 
[15:38:41]  preprocess finished in 79 ms 
[15:38:41]  webpack started ... 
[15:39:17]  webpack finished in 36.01 s 
[15:39:17]  uglifyjs started ... 
[15:39:17]  sass started ... 
[15:39:19]  sass finished in 1.79 s 
[15:39:19]  cleancss started ... 
[15:39:27]  cleancss finished in 8.04 s 
[15:39:43]  uglifyjs finished in 26.10 s 
[15:39:43]  postprocess started ... 
[15:39:43]  postprocess finished in 40 ms 
[15:39:43]  lint started ... 
[15:39:43]  build prod finished in 70.11 s 
> ionic cordova prepare
> cordova prepare

```

### Version info

**Angular:**
4.4.3
**Firebase:**
4.5.2
**AngularFire:**
5.0.0-rc.3
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

```
ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.0 
    ios-sim           : 6.0.0 
    Node              : v8.1.4
    npm               : 4.6.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

```

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by brndex** [comment] 2017-10-26 12:39
?

**Comment by larssn** [comment] 2017-11-03 09:28
Same'ish error in Angular 5:

```
Warning: Can't resolve all parameters for AngularFirestore in ./node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
Version: webpack 3.8.1
```

**Comment by Mironor** [comment] 2017-11-11 23:16
Looks like a duplicate of #1206

**Closed** 2017-11-13 19:03 UTC

**Comment by ssuperczynski** [comment] 2018-01-05 08:33
To anyone who has this error
https://stackoverflow.com/a/47051516/1168786
