### ISSUE TITLE
Broken - 1. Installation and Setup

### ISSUE THREAD

**Issue by christoferd** [angular/angularfire2#504] opened 2016-09-14 11:03 UTC
Hi, I have followed instructions in 1. Installation and Setup
Doesn't work.

Tried heaps of stuff, I enentually got it to say "app works!" however there are many error messages, "Cannot find namespace 'firebase'"

None of the suggestions in issues worked for me.

**Comment by davideast** [comment] 2016-09-14 11:34
Hi @christoferd. To help you I'll need more information.

What versions of AngularFire2, TypeScript, Angular, and Angular CLI are you using? What does your `tsconfig.json` look like?

**Comment by daimz** [comment] 2016-09-15 13:36
I had the same problem as @christoferd
`tsconfig.json` looks like this.
`{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}`
I'm using Angular CLi Webpack and have upgraded to Angular 2.0.0

**Comment by davideast** [comment] 2016-09-15 15:34
@daimz While the master branch is on 2.0 final, we have not released yet so you will see some problems. Have you read the updated quickstart? We recommend including `"firebase"` the `"types"` property array if you receive the `"Cannot find namespace 'firebase'"` error.

**Comment by mukesh51** [comment] 2016-09-15 17:50
@davideast I've created another pull request to update the quick start file. There is another error "Cannot find require". I discussed it with @katowulf and updated the quickstart. 

Need two more entries in src/typings.d.ts 

declare var require: any;
declare var module: any

**Comment by zakdances** [comment] 2016-09-15 21:31
@davideast 

My types array looks like this:

    "types": [ "jasmine", "firebase", "hammerjs" ]

and I'm still getting `Cannot find namespace 'firebase'`. I've also trying installing `@types/firebase` which doesn't help.

**Comment by davideast** [comment] 2016-09-15 23:11
@zakdances Installing `@types/firebase` will not help as they are not the official typings. The npm package ships with the typings.

Make sure you are on TypeScript 2.0.2 or above. And you can also try `"skipLibCheck": true` as a compiler option. 

Can you upload your project to a repo and link it here? I'd love to take a look.

**Comment by sobolewski** [comment] 2016-09-17 12:06
same problem here:
- i followed Installation instructions 0-6 and also added types to src/tsconfig.json as suggested

-> ng serve produces a long list of:

`ERROR in [default]
Cannot find type definition file for 'firebase'.`

(btw.: instruction 5. Inject AngularFire seems like a typo with the <MyApp>Componen- 
 `export class <MyApp>Component {
  constructor(af: AngularFire) {
  }` )

**Comment by hoenderdaal** [comment] 2016-09-17 20:38
I had the same issue on Windows 10 and adding the types array to tsconfig didn't help. On Ubuntu 16 it works fine after adding the types array.

The second time I tried it from scratch on Windows 10, I noticed installing angularfire2 required me to have python and the Microsoft build tools installed. I've been able to get it working for bcrypt, but couldn't get it to install without an error for angularfire2. I'm not sure if this is related.

**Comment by mukesh51** [comment] 2016-09-17 22:02
@hoenderdaal  Yes. I also had installation problems with Windows, but worked smoothly on Ubuntu 14.04 LTS.

**Comment by zakdances** [comment] 2016-09-19 00:12
@davideast After updating to `angular-cli: 1.0.0-beta.14`, I can't seem to reproduce this issue. I'll keep you updated if it should return. Thanks for the response.

**Comment by DarkerTV** [comment] 2016-09-22 03:55
I am getting the same problem using the `angular-cli: 1.0.0-beta.15` on Windows 10. My node version is `6.5.0` and my npm version is `3.10.3`. Also I already have tried to add types in `tsconfig.json` file but it seems to doesn't work anyway.

**Comment by christoferd** [comment] 2016-09-22 05:38
Thanks for the help, I have given up. 
I thought package managers were supposed to avoid these versioning issues.
BTW I'm on Windows 10 too, however, I doubt that is the cause.
I really don't like these things that rewrite javascript. I like javascript the way it is. 
I'm not afraid of typing extra characters. And, I don't like HTML in javascript files.

FWIW, **my favourite firebase tutorial** is the official firebase quickstart for web, it uses no extra special libraries or packages, and is written in **raw javascript :-)**

[https://github.com/firebase/quickstart-js](Firebase Quickstart for Web - JS only)

**Comment by dmastag** [comment] 2016-09-22 05:48
Well this merged Pull Request already fixes this issue.

https://github.com/angular/angularfire2/pull/538

Haven't tried it yet, but judging from the import in each ts file, this should have fixed this.

**Closed** 2016-09-26 22:19 UTC
