### ISSUE TITLE
Angularfire rc6 +firebase 4.9 FieldPath issue

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire2#1448] opened 2018-01-29 11:00 UTC
After installation of the new version, there seems to be an issue:

 Argument of type 'FieldPath' is not assignable to parameter of type 'string | FieldPath'.
  Type 'firebase.firestore.FieldPath' is not assignable to type 'FieldPath'.
    Property 'isEqual' is missing in type 'FieldPath'.

this for the line:
orgObs = this.afs.collection('organisations', ref => ref.where(new firestore.FieldPath('manager_list', this.userService.userModel.email), '==', true));

after removal of the isEqual(other: FieldPath): boolean;
in firestore-types/index.d.ts it seems to work.

**Comment by LanderBeeuwsaert** [comment] 2018-01-29 11:00
(same issue seems to be present with the .batch() type

**Comment by phra** [comment] 2018-01-29 11:20
related to #1449 ?

**Comment by LanderBeeuwsaert** [comment] 2018-01-29 11:22
I wouldn't think so, it seems more an issue with the typescript definitions (on first look, didn't dig very deep into it)

**Comment by jwuliger** [comment] 2018-01-31 22:17
Hello guys,

I have been pulling my hair out on this issue for a few days now. 

After the release of version RC.6, I upgraded my Angular CLI/[@nrwl/nx](https://github.com/nrwl/nx) Workspace/Mono Repo based app. Everything workes great on a PC running windows using AF RC.6 and Firebase 4.9.0 and/or 4.8.2.

I have a few developers running a common build of Linux and a couple devs running the latest version of MacOS. For whatever reason, no matter what I try, or what they try - WebPack/NG CLI fails to compile a simple `ng -serve` on anything put a windows based machine.

Node: 8.9.4
OS: darwin x64 (Latest MacOs High Sierra)
NPM: 5.6.0

All research I have done points to this issue being fixed in the RC.6 release. Which it seems to be. 

However, I still get this error when trying to run the same build that is working on my PC - on my Mac.

```
ERROR in ./node_modules/@firebase/polyfill/index.ts
Module build failed: Error: /Users/jared/Documents/My Code Projects/viven-health-mono-repo/node_modules/@firebase/polyfill/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/jared/Documents/My Code Projects/viven-health-mono-repo/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:672:23)
    at plugin.done.then (/Users/jared/Documents/My Code Projects/viven-health-mono-repo/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./node_modules/firebase/app/index.js 17:0-29
 @ ./libs/data/src/data.ts
 @ ./libs/data/index.ts
 @ ./apps/site/src/app/core/core.module.ts
 @ ./apps/site/src/app/app.module.ts
 @ ./apps/site/src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./apps/site/src/main.ts
```

I have tried many things including my entire repo's path structure and so on. Any advice/help would be invaluable.

Thanks for your time.

**Comment by jamesdaniels** [comment] 2018-05-04 21:18
Please update your Firebase JS SDK version and the types, should fix these issues. If you're continuing to have problems please open a new issue with reproduction steps.

**Closed by jamesdaniels** 2018-05-04 21:18 UTC
