### ISSUE TITLE
Module not found: Error: Can't resolve '../../angularfire2/firestore'

### ISSUE THREAD

**Issue by Beeruot** [angular/angularfire2#1362] opened 2017-11-26 19:28 UTC
### Version info

Angular:*4.1.3*

Firebase:*4.6.0*

AngularFire:*5.0.0-rc.3*

Ionic:*3.19*

### How to reproduce these conditions

ionic cordova build <platform> **--prod**

working great without --prod.

### Debug output

**Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/firestore'......**

This error is killing me. I tried everything.
I can not downgrade to v4 because I need FireStore.

**Comment by davideast** [comment] 2017-11-27 18:57
Hey @Beeruot! This is not a bug with AngularFire but with the ionic build process. I think this is fixed in the latest CLI release. Can you try upgrading and see if it fixes? If not please file a bug with their repo.

**Closed by davideast** 2017-11-27 18:57 UTC
