### ISSUE TITLE
CollectionReference.doc function path should be optional

### ISSUE THREAD

**Issue by OmriAbu** [angular/angularfire2#1974] opened 2018-12-15 18:17 UTC
### Version info

**Angular:** 7.1.2

**Firebase:** 5.6.0

**AngularFire:** 5.1.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**

Example code:
``` typescript
const ref = this.afs.collection(this.collectionRef).doc();
```

Failing on the following error:
```
Expected 1 arguments, but got 0.ts(2554)
collection.d.ts(18, 12): An argument for 'path' was not provided.
```

But should be valid per firebase documentation and source:
Add doc example https://firebase.google.com/docs/firestore/manage-data/add-data
Source definition of doc function https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L1951

### Debug output

** Errors in the JavaScript console **
```
ERROR Error: Uncaught (in promise): FirebaseError: [code=invalid-argument]: Function CollectionReference.doc() requires its first argument to be of type non-empty string, but it was: undefined
FirebaseError: Function CollectionReference.doc() requires its first argument to be of type non-empty string, but it was: undefined
```

### Expected behavior

Doc reference should be created per firebase documentation

### Actual behavior
Invalid argument error thrown

### Fix

path argument should be optional in https://github.com/angular/angularfire2/blob/master/src/firestore/collection/collection.ts#L141

**Comment by codediodeio** [comment] 2018-12-19 02:43
I agree, this should align with the Firebase SDK. I'm going to submit a PR tonight, but a potential workaround is to use a pattern like this: 

```
const id = this.afs.createId();
const ref = this.afs.collection(this.collectionRef).doc(id);
```

**Comment by yuliankarapetkov** [comment] 2019-01-08 12:34
+1 Is this going to be fixed in future releases?

**Comment by rmolinamir** [comment] 2019-01-18 19:02
Ran into this earlier as well, had to pass a randomly generated string using date constructors to force creation in the database as a workaround, but was totally caught off guard by this error thrown since it contradicts the docs.

**Comment by cwborion** [comment] 2019-02-08 06:58
I am getting this error as well, when trying to delete a document, however, it is working in another place in the app, so I am extra confused.

**Comment by rmolinamir** [comment] 2019-02-08 07:00
If you’re getting this error when trying to delete, I think you might be sending an undefined id.

**Comment by cwborion** [comment] 2019-02-08 07:14
ah yes you were right! Thank you! Because of the type and positioning of the component I needed to access the id differently

**Comment by cedvdb** [comment] 2019-04-16 16:51
workaround for me:

`const doc = this.afStore.collection<Event>(Coll.EVENT).doc(undefined);`

**Comment by mattrmaydew** [comment] 2019-05-04 05:19
undefined id.  doc['.key'] wasn't working for me any longer had to go doc.id

**Comment by gildniy** [comment] 2019-05-24 21:43
What if one does this: `.doc('')` instead?! 
Me I got this error claiming to have been undefined then I first checked if the doc id exists then I passed that line query inside the if statement on truthy. `if(id.lenght) ....doc(id);`

**Comment by jamesdaniels** [comment] 2019-05-24 23:39
This will be addressed in `5.2`, tossed it in real quick as c2354f8. #2086

**Closed by jamesdaniels** 2019-05-24 23:39 UTC

**Comment by schankam** [comment] 2019-06-21 08:45
Mhh, just updated to @angular/fire 5.2 and firebase 6.2.1, and the problem is still here for me.

I'm getting the following error:

`CollectionReference.doc() requires its first argument to be of type non-empty string, but it was: undefined`

when trying to set a batch write operation calling "set", with ```this.afs.collection<Offer>('offers').doc().ref``` .

The solution given [here](https://github.com/angular/angularfire2/issues/1974#issuecomment-448449448) works for me... But calling an empty doc on a collection works well with the firebase-admin SDK to create new documents (in case of a batch write using "set"for example), I was expecting the same with the JS client....

**Comment by Julieng50** [comment] 2019-12-06 12:46
Here is the bug :
````
CollectionReference.prototype.doc = function (pathString) {
    validateBetweenNumberOfArgs('CollectionReference.doc', arguments, 0, 1);
    // We allow omission of 'pathString' but explicitly prohibit passing in both
    // 'undefined' and 'null'.
    if (arguments.length === 0) { // Impossible because there is 1 argument, even if not defined (undefined)
        pathString = AutoId.newId();
    }
    validateArgType('CollectionReference.doc', 'non-empty string', 1, pathString);
    if (pathString === '') {
        throw new FirestoreError(Code.INVALID_ARGUMENT, 'Document path must be a non-empty string');
    }
    var path = ResourcePath.fromString(pathString);
    return DocumentReference.forPath(this._query.path.child(path), this.firestore);
};
````

**Comment by elongvieira** [comment] 2020-02-18 14:40
It is working for me:

`this.db.collection(collectionn).add(obj);`
or
`this.db.collection(this.collectionMain).doc(this.db.createId()).set(obj)`

**Comment by elongvieira** [comment] 2020-02-18 14:41
It is working for me:

`this.db.collection(collectionn).add(obj);`
or
`this.db.collection(this.collectionMain).doc(this.db.createId()).set(obj)`
