### ISSUE TITLE
Cannot find type definition file for 'firebase'.

### ISSUE THREAD

**Issue by clust3rsekt0r** [angular/angularfire2#609] opened 2016-10-12 03:52 UTC
Hi all awesome project but like always with javascript, you start coding after 1 year trying to setup your dev env, I follow the setup doc but still getting this error, I try the two fixes but this one is realed to a lot of files.

Windows10
Node 6.5.0
angular-cli: 1.0.0-beta.17

ERROR in [default] 
Cannot find type definition file for 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\angularfire2.d.ts:13:65 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\angularfire2.d.ts:15:45 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:9:39 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:10:51 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:10:91 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:11:50 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:11:118 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth.d.ts:14:55 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:6:81 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:8:48 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:13:45 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:40:10 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:42:13 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:43:13 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:44:14 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:45:15 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:48:54 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\auth_backend.d.ts:48:84 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\firebase_sdk_auth_backend.d.ts:5:13 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\firebase_sdk_auth_backend.d.ts:6:24 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\firebase_sdk_auth_backend.d.ts:14:72 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\firebase_sdk_auth_backend.d.ts:16:35 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\auth\firebase_sdk_auth_backend.d.ts:17:36 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\database.d.ts:8:28 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\database.d.ts:9:30 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_factory.d.ts:3:73 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_factory.d.ts:3:103 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:6:49 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:6:79 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:8:10 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:8:40 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:9:22 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:9:52 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:11:20 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:12:52 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:13:38 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_list_observable.d.ts:14:82 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_object_factory.d.ts:3:75 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_object_observable.d.ts:7:101 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_object_observable.d.ts:9:21 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_object_observable.d.ts:10:27 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\database\firebase_object_observable.d.ts:11:14 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\interfaces.d.ts:9:22 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\interfaces.d.ts:10:25 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\interfaces.d.ts:11:25 
Cannot find namespace 'firebase'.

ERROR in [default] C:\angprojects\ng-fire2\node_modules\angularfire2\interfaces.d.ts:12:34 
Cannot find namespace 'firebase'.

**Comment by cre8** [comment] 2016-10-12 06:11
the easiest way is to import firebase in your main component like 
`import *as firebase from 'firebase';`
but then lint will say firebase is an unsued import, so it's better to import it in the types file
`/node_modules/angularfire2/angularfire2.d.ts` and add `import *as firebase from 'firebase'`

**Comment by mukesh51** [comment] 2016-10-12 08:35
@clust3rsekt0r Even though errors are thrown on Windows 10, the connectivity with Firebase should work as expected.

Duplicate of #525 . Also check #569 

@davideast FYI

**Comment by katowulf** [comment] 2016-10-12 15:59
Closing because it's a dup and because it does not follow our issue template. In the future, please follow the issue template (which includes a note to search for similar issues).

**Closed by katowulf** 2016-10-12 15:59 UTC
