### ISSUE TITLE
automaticDataCollectionEnabled' is missing in type 'FirebaseApp'

### ISSUE THREAD

**Issue by MingyuJeon** [angular/angularfire2#1571] opened 2018-04-20 09:26 UTC
### Version info

**Angular:** 5.2.9

**Firebase:** ^4.13.0

**AngularFire2:** ^5.0.0-rc.6.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**Ionic/Cordova

### How to reproduce these conditions
**package.json**
```
"dependencies": {
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "angularfire2": "^5.0.0-rc.6.0",
    "firebase": "^4.13.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "promise-polyfill": "^7.1.2",
    "rxjs": "5.5.8",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  }
```

### Debug output

**Errors in the JavaScript console**
```
typescript: node_modules/angularfire2/firebase.app.module.d.ts, line: 10 
            Class 'FirebaseApp' incorrectly implements interface 'FirebaseApp'. Property 
            'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'. 

       L9:  export declare const FirebaseAppConfigToken: InjectionToken;
      L10:  export declare class FirebaseApp implements FBApp {
      L11:      name: string;

```

### Expected behavior
Ionic compile would complete with any errors

### Actual behavior
Because `automaticDataCollectionEnabled` is missing in type 'FirebaseApp', error occurs.

**Comment by Tamango92** [comment] 2018-04-20 12:25
This issue is related to latest firebase update [https://github.com/firebase/firebase-js-sdk/commit/7c1aa4470c0f5474b11fe57ada4edff65ed90adc](url)

Temporary solution is to set version of **firebase** in your projects package.json to 4.12.1
```
"dependencies": {
     "firebase":"4.12.1",
     "angularfire2":"^5.0.0-rc.6"
}
```

**Comment by zverbeta** [comment] 2018-04-20 14:56
@Tamango92 Does he work for you? I trying your solution and it doesn't working

**Comment by zverbeta** [comment] 2018-04-20 15:17
I have installed ```"@firebase/app": "^0.1.10"``` and it's working

**Comment by MingyuJeon** [comment] 2018-04-20 18:09
@Tamango92 actually I was using `firebase 4.12.1`. So it didn't work for me.
But I would solve this issue @zverbeta 's solution.
Thank you.
#1572 and I sent PR about this.

**Comment by Tamango92** [comment] 2018-04-20 18:17
It worked for me, but with ‘npm cache clean’ before installing

**Comment by okeefem2** [comment] 2018-04-21 01:07
I can confirm this worked for me as well.

**Comment by madhu72** [comment] 2018-04-22 13:52
Compiling successfully but, getting issue with Google Authentication Provider

ERROR TypeError: Cannot read property 'GoogleAuthProvider' of undefined

**Comment by qorbani** [comment] 2018-04-23 18:00
Simple 1-line patch for lazy people like 😊

`sed -i.bak 's|^}$|    automaticDataCollectionEnabled: false;}|' node_modules/angularfire2/firebase.app.module.d.ts`

**Comment by opiepj** [comment] 2018-04-23 18:11
@Tamango92 Downgraded, but facing more issues
1. `npm cache clean`
2. 
```json
"dependencies": {
     "firebase":"4.12.1",
     "angularfire2":"^5.0.0-rc.6"
}
```

Now I'm asked to install all `@firebase` modules, for example:
```
[11:08:28]  typescript: node_modules/angularfire2/firestore/observable/fromRef.d.ts, line: 1 
            Cannot find module '@firebase/firestore-types'. 

       L1:  import { DocumentReference, Query, QuerySnapshot, DocumentSnapshot } from '@firebase/firestore-types';
       L2:  import { Observable } from 'rxjs/Observable';

```

**Comment by nguyentk90** [comment] 2018-04-24 03:15
I have seen this change already merged so we need to wait for a new release of angularfire2 on npm.

In the mean time, just update `@firebase/app": "0.1.10"`. It works for me.

**Comment by dodekx** [comment] 2018-04-24 07:13
for me this config work:

> "firebase": "^4.13.1",
    "angularfire2": "^5.0.0-rc.6",
    "@firebase/app": "0.1.10",
    "@firebase/auth": "0.4.1",
    "@firebase/database": "0.2.1",
    "@firebase/firestore": "0.3.7",
    "@firebase/functions": "0.1.0",
    "@firebase/messaging": "0.2.3",
    "@firebase/polyfill": "0.3.0",
    "@firebase/storage": "0.1.8",
    "ngrx-store-freeze": "^0.2.2",

>

**Comment by arturasgusevas** [comment] 2018-04-24 17:02
Found this fix here: https://stackoverflow.com/questions/49963223/property-automaticdatacollectionenabled-is-missing-in-type-firebaseapp

"export declare class FirebaseApp implements FBApp {
name: string;
options: {};
**automaticDataCollectionEnabled: boolean; // this is the missing line**
auth: () => FirebaseAuth;
database: () => FirebaseDatabase;
messaging: () => FirebaseMessaging;
storage: () => FirebaseStorage;
delete: () => Promise<any>;
firestore: () => FirebaseFirestore;
}
also add @firebase/app

npm i -S @firebase/app"

**Comment by cicode225** [comment] 2018-04-25 09:59
Same issue solved as suggested above...
At first, I had : 
```
"dependencies": {
     "firebase":"^4.13.1",
     "angularfire2":"^5.0.0-rc.6"
}
```

Then after visiting here I did : 

1. `npm uninstall firebase`
2. `npm clean cache --force`
3. `npm install firebase@4.12.1`

As a result, it all works well for me. I got : 

```
"dependencies": {
     "firebase":"^4.12.1",
     "angularfire2":"^5.0.0-rc.6"
}
```

**Comment by junweipan** [comment] 2018-04-26 08:35
It is worked for @cicode225 ,Thanks a lot
Same issue solved as suggested above...
At first, I had :

"dependencies": {
     "firebase":"^4.13.1",
     "angularfire2":"^5.0.0-rc.6"
}
Then after visiting here I did :

npm uninstall firebase
npm clean cache --force
npm install firebase@4.12.1
As a result, it all works well for me. I got :

"dependencies": {
     "firebase":"^4.12.1",
     "angularfire2":"^5.0.0-rc.6"
}

**Closed** 2018-04-26 23:00 UTC

**Comment by yuehernkang** [comment] 2018-04-28 04:00
@cicode225  thanks it work

**Comment by torresdaniel11** [comment] 2018-05-01 05:32
@cicode225  Thank you!!! solved mi problem

**Comment by tecxperts** [comment] 2018-05-01 18:59
@cicode225 works fine thanks.....but i had to use 'npm cache clean --force' :)

**Comment by josephprasanth** [comment] 2018-05-18 18:09
Thank you cicode225  .... This saved my work

**Comment by opiepj** [comment] 2018-05-31 23:31
@cicode225 nice!
